// @ts-nocheck
import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  console.log('VISION R+ — Chargement des plans comptables...');

  const comptes = [
    // ══ OHADA CLASSE 1 ══
    { code: '101', label: 'Capital social', type: 'passif', system: 'ohada' },
    { code: '1011', label: 'Capital souscrit non appelé', type: 'passif', system: 'ohada' },
    { code: '1012', label: 'Capital souscrit appelé non versé', type: 'passif', system: 'ohada' },
    { code: '1013', label: 'Capital souscrit appelé versé non amorti', type: 'passif', system: 'ohada' },
    { code: '102', label: 'Capital par dotation', type: 'passif', system: 'ohada' },
    { code: '103', label: 'Capital personnel', type: 'passif', system: 'ohada' },
    { code: '104', label: "Compte de l'exploitant", type: 'passif', system: 'ohada' },
    { code: '1041', label: 'Apports temporaires', type: 'passif', system: 'ohada' },
    { code: '105', label: 'Primes liées aux capitaux propres', type: 'passif', system: 'ohada' },
    { code: '1051', label: "Primes d'émission", type: 'passif', system: 'ohada' },
    { code: '1052', label: "Primes d'apport", type: 'passif', system: 'ohada' },
    { code: '1053', label: 'Primes de fusion', type: 'passif', system: 'ohada' },
    { code: '106', label: 'Écarts de réévaluation', type: 'passif', system: 'ohada' },
    { code: '111', label: 'Réserve légale', type: 'passif', system: 'ohada' },
    { code: '112', label: 'Réserves statutaires ou contractuelles', type: 'passif', system: 'ohada' },
    { code: '118', label: 'Autres réserves', type: 'passif', system: 'ohada' },
    { code: '120', label: "Résultat de l'exercice", type: 'passif', system: 'ohada' },
    { code: '121', label: 'Report à nouveau créditeur', type: 'passif', system: 'ohada' },
    { code: '129', label: 'Report à nouveau débiteur', type: 'passif', system: 'ohada' },
    { code: '130', label: "Résultat en instance d'affectation", type: 'passif', system: 'ohada' },
    { code: '131', label: 'Résultat net bénéfice', type: 'passif', system: 'ohada' },
    { code: '139', label: 'Résultat net perte', type: 'passif', system: 'ohada' },
    { code: '141', label: "Subventions d'équipement État", type: 'passif', system: 'ohada' },
    { code: '1411', label: "Subventions d'équipement État central", type: 'passif', system: 'ohada' },
    { code: '1417', label: 'Subventions organismes internationaux', type: 'passif', system: 'ohada' },
    { code: '148', label: "Autres subventions d'investissement", type: 'passif', system: 'ohada' },
    { code: '151', label: 'Amortissements dérogatoires', type: 'passif', system: 'ohada' },
    { code: '152', label: 'Plus-values de cession à réinvestir', type: 'passif', system: 'ohada' },
    { code: '154', label: 'Provision spéciale de réévaluation', type: 'passif', system: 'ohada' },
    { code: '161', label: 'Emprunts obligataires', type: 'passif', system: 'ohada' },
    { code: '1611', label: 'Emprunts obligataires ordinaires', type: 'passif', system: 'ohada' },
    { code: '1612', label: 'Emprunts obligataires convertibles', type: 'passif', system: 'ohada' },
    { code: '162', label: 'Emprunts auprès des établissements de crédit', type: 'passif', system: 'ohada' },
    { code: '163', label: "Avances reçues de l'État", type: 'passif', system: 'ohada' },
    { code: '164', label: 'Avances reçues et comptes courants bloqués', type: 'passif', system: 'ohada' },
    { code: '165', label: 'Dépôts et cautionnements reçus', type: 'passif', system: 'ohada' },
    { code: '166', label: 'Intérêts courus sur emprunts', type: 'passif', system: 'ohada' },
    { code: '168', label: 'Autres emprunts et dettes', type: 'passif', system: 'ohada' },
    { code: '172', label: 'Emprunts équivalents crédit-bail immobilier', type: 'passif', system: 'ohada' },
    { code: '173', label: 'Emprunts équivalents crédit-bail mobilier', type: 'passif', system: 'ohada' },
    { code: '181', label: 'Dettes liées à des participations', type: 'passif', system: 'ohada' },
    { code: '191', label: 'Provisions pour litiges', type: 'passif', system: 'ohada' },
    { code: '192', label: 'Provisions pour garanties données aux clients', type: 'passif', system: 'ohada' },
    { code: '194', label: 'Provisions pour pertes de change', type: 'passif', system: 'ohada' },
    { code: '195', label: 'Provisions pour impôts', type: 'passif', system: 'ohada' },
    { code: '196', label: 'Provisions pour pensions et obligations', type: 'passif', system: 'ohada' },
    { code: '197', label: 'Provisions pour charges à répartir', type: 'passif', system: 'ohada' },
    { code: '1971', label: 'Provisions pour grosses réparations', type: 'passif', system: 'ohada' },
    { code: '198', label: 'Autres provisions financières pour risques', type: 'passif', system: 'ohada' },
    // ══ OHADA CLASSE 2 ══
    { code: '201', label: "Frais d'établissement", type: 'actif', system: 'ohada' },
    { code: '2011', label: 'Frais de constitution', type: 'actif', system: 'ohada' },
    { code: '2012', label: 'Frais de prospection', type: 'actif', system: 'ohada' },
    { code: '2013', label: 'Frais de publicité et de lancement', type: 'actif', system: 'ohada' },
    { code: '2015', label: 'Frais de modification du capital', type: 'actif', system: 'ohada' },
    { code: '2017', label: 'Frais de restructuration', type: 'actif', system: 'ohada' },
    { code: '202', label: 'Charges à répartir sur plusieurs exercices', type: 'actif', system: 'ohada' },
    { code: '2021', label: 'Charges différées', type: 'actif', system: 'ohada' },
    { code: '2022', label: "Frais d'acquisition d'immobilisations", type: 'actif', system: 'ohada' },
    { code: '211', label: 'Frais de recherche et de développement', type: 'actif', system: 'ohada' },
    { code: '212', label: 'Brevets licences concessions', type: 'actif', system: 'ohada' },
    { code: '213', label: 'Logiciels', type: 'actif', system: 'ohada' },
    { code: '214', label: 'Marques', type: 'actif', system: 'ohada' },
    { code: '215', label: 'Fonds commercial', type: 'actif', system: 'ohada' },
    { code: '216', label: 'Droit au bail', type: 'actif', system: 'ohada' },
    { code: '218', label: 'Autres droits et valeurs incorporels', type: 'actif', system: 'ohada' },
    { code: '219', label: 'Immobilisations incorporelles en cours', type: 'actif', system: 'ohada' },
    { code: '221', label: 'Terrains agricoles et forestiers', type: 'actif', system: 'ohada' },
    { code: '222', label: 'Terrains nus', type: 'actif', system: 'ohada' },
    { code: '2221', label: 'Terrains à bâtir', type: 'actif', system: 'ohada' },
    { code: '223', label: 'Terrains bâtis', type: 'actif', system: 'ohada' },
    { code: '2231', label: 'Terrains bâtis industriels', type: 'actif', system: 'ohada' },
    { code: '2232', label: 'Terrains bâtis administratifs', type: 'actif', system: 'ohada' },
    { code: '224', label: 'Travaux de mise en valeur des terrains', type: 'actif', system: 'ohada' },
    { code: '225', label: 'Terrains de gisement', type: 'actif', system: 'ohada' },
    { code: '226', label: 'Terrains aménagés', type: 'actif', system: 'ohada' },
    { code: '228', label: 'Autres terrains', type: 'actif', system: 'ohada' },
    { code: '229', label: 'Aménagements de terrains en cours', type: 'actif', system: 'ohada' },
    { code: '231', label: 'Bâtiments sur sol propre', type: 'actif', system: 'ohada' },
    { code: '2311', label: 'Bâtiments industriels', type: 'actif', system: 'ohada' },
    { code: '2312', label: 'Bâtiments agricoles', type: 'actif', system: 'ohada' },
    { code: '2313', label: 'Bâtiments administratifs et commerciaux', type: 'actif', system: 'ohada' },
    { code: '2314', label: 'Bâtiments logements du personnel', type: 'actif', system: 'ohada' },
    { code: '232', label: "Bâtiments sur sol d'autrui", type: 'actif', system: 'ohada' },
    { code: '233', label: "Ouvrages d'infrastructure", type: 'actif', system: 'ohada' },
    { code: '2331', label: 'Voies de terre', type: 'actif', system: 'ohada' },
    { code: '2332', label: 'Voies de fer', type: 'actif', system: 'ohada' },
    { code: '2333', label: "Voies d'eau", type: 'actif', system: 'ohada' },
    { code: '234', label: 'Installations techniques', type: 'actif', system: 'ohada' },
    { code: '2341', label: 'Installations complexes sur sol propre', type: 'actif', system: 'ohada' },
    { code: '235', label: 'Aménagements de bureaux', type: 'actif', system: 'ohada' },
    { code: '237', label: 'Bâtiments mis en concession', type: 'actif', system: 'ohada' },
    { code: '238', label: 'Autres installations et agencements', type: 'actif', system: 'ohada' },
    { code: '239', label: 'Bâtiments et installations en cours', type: 'actif', system: 'ohada' },
    { code: '241', label: 'Matériel et outillage industriel et commercial', type: 'actif', system: 'ohada' },
    { code: '2411', label: 'Matériel industriel', type: 'actif', system: 'ohada' },
    { code: '2412', label: 'Outillage industriel', type: 'actif', system: 'ohada' },
    { code: '2413', label: 'Matériel commercial', type: 'actif', system: 'ohada' },
    { code: '2414', label: 'Outillage commercial', type: 'actif', system: 'ohada' },
    { code: '242', label: 'Matériel et outillage agricole', type: 'actif', system: 'ohada' },
    { code: '244', label: 'Matériel et mobilier', type: 'actif', system: 'ohada' },
    { code: '2441', label: 'Matériel de bureau', type: 'actif', system: 'ohada' },
    { code: '2442', label: 'Matériel informatique', type: 'actif', system: 'ohada' },
    { code: '2443', label: 'Matériel bureautique', type: 'actif', system: 'ohada' },
    { code: '2444', label: 'Mobilier de bureau', type: 'actif', system: 'ohada' },
    { code: '2446', label: 'Matériel immeubles de rapport', type: 'actif', system: 'ohada' },
    { code: '2447', label: 'Matériel logements du personnel', type: 'actif', system: 'ohada' },
    { code: '245', label: 'Matériel de transport', type: 'actif', system: 'ohada' },
    { code: '2451', label: 'Matériel automobile', type: 'actif', system: 'ohada' },
    { code: '2452', label: 'Matériel ferroviaire', type: 'actif', system: 'ohada' },
    { code: '2453', label: 'Matériel fluvial et lagunaire', type: 'actif', system: 'ohada' },
    { code: '2454', label: 'Matériel naval', type: 'actif', system: 'ohada' },
    { code: '2455', label: 'Matériel aérien', type: 'actif', system: 'ohada' },
    { code: '2458', label: 'Autres matériels de transport', type: 'actif', system: 'ohada' },
    { code: '246', label: 'Immobilisations animales et agricoles', type: 'actif', system: 'ohada' },
    { code: '247', label: 'Agencements et aménagements du matériel', type: 'actif', system: 'ohada' },
    { code: '248', label: 'Autres matériels', type: 'actif', system: 'ohada' },
    { code: '249', label: 'Matériel en cours', type: 'actif', system: 'ohada' },
    { code: '251', label: 'Avances sur immobilisations incorporelles', type: 'actif', system: 'ohada' },
    { code: '252', label: 'Avances sur immobilisations corporelles', type: 'actif', system: 'ohada' },
    { code: '261', label: 'Titres de participation contrôle exclusif', type: 'actif', system: 'ohada' },
    { code: '262', label: 'Titres de participation contrôle conjoint', type: 'actif', system: 'ohada' },
    { code: '263', label: 'Titres de participation influence notable', type: 'actif', system: 'ohada' },
    { code: '265', label: 'Participations organismes professionnels', type: 'actif', system: 'ohada' },
    { code: '266', label: 'Parts dans des GIE', type: 'actif', system: 'ohada' },
    { code: '268', label: 'Autres titres de participation', type: 'actif', system: 'ohada' },
    { code: '271', label: 'Prêts et créances non commerciales', type: 'actif', system: 'ohada' },
    { code: '2711', label: 'Prêts participatifs', type: 'actif', system: 'ohada' },
    { code: '2712', label: 'Prêts aux associés', type: 'actif', system: 'ohada' },
    { code: '272', label: 'Prêts au personnel', type: 'actif', system: 'ohada' },
    { code: '2721', label: 'Prêts immobiliers', type: 'actif', system: 'ohada' },
    { code: '274', label: 'Titres immobilisés', type: 'actif', system: 'ohada' },
    { code: '275', label: 'Dépôts et cautionnements versés', type: 'actif', system: 'ohada' },
    { code: '2751', label: 'Dépôts pour loyers', type: 'actif', system: 'ohada' },
    { code: '2752', label: "Dépôts pour l'électricité", type: 'actif', system: 'ohada' },
    { code: '2753', label: "Dépôts pour l'eau", type: 'actif', system: 'ohada' },
    { code: '2755', label: 'Dépôts pour le téléphone', type: 'actif', system: 'ohada' },
    { code: '2756', label: 'Cautionnements sur marchés publics', type: 'actif', system: 'ohada' },
    { code: '276', label: 'Intérêts courus immobilisations financières', type: 'actif', system: 'ohada' },
    { code: '277', label: 'Créances rattachées à des participations', type: 'actif', system: 'ohada' },
    { code: '278', label: 'Immobilisations financières diverses', type: 'actif', system: 'ohada' },
    { code: '281', label: 'Amortissements immobilisations incorporelles', type: 'actif', system: 'ohada' },
    { code: '2811', label: 'Amort. frais de recherche et développement', type: 'actif', system: 'ohada' },
    { code: '2812', label: 'Amort. brevets licences concessions', type: 'actif', system: 'ohada' },
    { code: '2813', label: 'Amort. logiciels', type: 'actif', system: 'ohada' },
    { code: '2814', label: 'Amort. marques', type: 'actif', system: 'ohada' },
    { code: '2815', label: 'Amort. fonds commercial', type: 'actif', system: 'ohada' },
    { code: '283', label: 'Amort. bâtiments et installations', type: 'actif', system: 'ohada' },
    { code: '2831', label: 'Amort. bâtiments sur sol propre', type: 'actif', system: 'ohada' },
    { code: '2832', label: "Amort. bâtiments sur sol d'autrui", type: 'actif', system: 'ohada' },
    { code: '2833', label: "Amort. ouvrages d'infrastructure", type: 'actif', system: 'ohada' },
    { code: '2834', label: 'Amort. installations techniques', type: 'actif', system: 'ohada' },
    { code: '284', label: 'Amortissements du matériel', type: 'actif', system: 'ohada' },
    { code: '2841', label: 'Amort. matériel et outillage industriel', type: 'actif', system: 'ohada' },
    { code: '2844', label: 'Amort. matériel et mobilier', type: 'actif', system: 'ohada' },
    { code: '2845', label: 'Amort. matériel de transport', type: 'actif', system: 'ohada' },
    { code: '291', label: 'Dépréciations immobilisations incorporelles', type: 'actif', system: 'ohada' },
    { code: '292', label: 'Dépréciations des terrains', type: 'actif', system: 'ohada' },
    { code: '293', label: 'Dépréciations bâtiments et installations', type: 'actif', system: 'ohada' },
    { code: '294', label: 'Dépréciations du matériel', type: 'actif', system: 'ohada' },
    { code: '295', label: 'Dépréciations avances sur immobilisations', type: 'actif', system: 'ohada' },
    { code: '296', label: 'Dépréciations titres de participation', type: 'actif', system: 'ohada' },
    { code: '297', label: 'Dépréciations autres immobilisations financières', type: 'actif', system: 'ohada' },
    // ══ OHADA CLASSE 3 ══
    { code: '311', label: 'Marchandises A', type: 'actif', system: 'ohada' },
    { code: '3111', label: 'Marchandises A1', type: 'actif', system: 'ohada' },
    { code: '312', label: 'Marchandises B', type: 'actif', system: 'ohada' },
    { code: '318', label: 'Marchandises HAO', type: 'actif', system: 'ohada' },
    { code: '321', label: 'Matières premières A', type: 'actif', system: 'ohada' },
    { code: '322', label: 'Matières premières B', type: 'actif', system: 'ohada' },
    { code: '323', label: 'Fournitures', type: 'actif', system: 'ohada' },
    { code: '331', label: 'Matières consommables', type: 'actif', system: 'ohada' },
    { code: '332', label: "Fournitures d'atelier et d'usine", type: 'actif', system: 'ohada' },
    { code: '333', label: 'Fournitures de magasin', type: 'actif', system: 'ohada' },
    { code: '334', label: 'Fournitures de bureau', type: 'actif', system: 'ohada' },
    { code: '335', label: 'Emballages', type: 'actif', system: 'ohada' },
    { code: '3351', label: 'Emballages perdus', type: 'actif', system: 'ohada' },
    { code: '341', label: 'Produits en cours', type: 'actif', system: 'ohada' },
    { code: '342', label: 'Travaux en cours', type: 'actif', system: 'ohada' },
    { code: '351', label: 'Études en cours', type: 'actif', system: 'ohada' },
    { code: '352', label: 'Prestations de services en cours', type: 'actif', system: 'ohada' },
    { code: '361', label: 'Produits finis A', type: 'actif', system: 'ohada' },
    { code: '362', label: 'Produits finis B', type: 'actif', system: 'ohada' },
    { code: '371', label: 'Produits intermédiaires', type: 'actif', system: 'ohada' },
    { code: '372', label: 'Produits résiduels', type: 'actif', system: 'ohada' },
    { code: '381', label: 'Marchandises en cours de route', type: 'actif', system: 'ohada' },
    { code: '391', label: 'Dépréciations stocks de marchandises', type: 'actif', system: 'ohada' },
    { code: '392', label: 'Dépréciations matières premières', type: 'actif', system: 'ohada' },
    { code: '393', label: 'Dépréciations autres approvisionnements', type: 'actif', system: 'ohada' },
    { code: '396', label: 'Dépréciations stocks de produits finis', type: 'actif', system: 'ohada' },
    // ══ OHADA CLASSE 4 ══
    { code: '401', label: 'Fournisseurs dettes en compte', type: 'passif', system: 'ohada' },
    { code: '4011', label: 'Fournisseurs ordinaires', type: 'passif', system: 'ohada' },
    { code: '4012', label: 'Fournisseurs groupe', type: 'passif', system: 'ohada' },
    { code: '4013', label: 'Fournisseurs sous-traitants', type: 'passif', system: 'ohada' },
    { code: '4017', label: 'Fournisseurs retenues de garantie', type: 'passif', system: 'ohada' },
    { code: '402', label: 'Fournisseurs effets à payer', type: 'passif', system: 'ohada' },
    { code: '408', label: 'Fournisseurs factures non parvenues', type: 'passif', system: 'ohada' },
    { code: '4081', label: 'Fournisseurs FNP exploitation', type: 'passif', system: 'ohada' },
    { code: '409', label: 'Fournisseurs débiteurs avances', type: 'actif', system: 'ohada' },
    { code: '4091', label: 'Fournisseurs avances et acomptes versés', type: 'actif', system: 'ohada' },
    { code: '4094', label: 'Fournisseurs créances emballages', type: 'actif', system: 'ohada' },
    { code: '4098', label: 'Rabais remises ristournes à obtenir', type: 'actif', system: 'ohada' },
    { code: '411', label: 'Clients', type: 'actif', system: 'ohada' },
    { code: '4111', label: 'Clients ordinaires', type: 'actif', system: 'ohada' },
    { code: '4112', label: 'Clients groupe', type: 'actif', system: 'ohada' },
    { code: '4114', label: 'Clients État et collectivités publiques', type: 'actif', system: 'ohada' },
    { code: '4117', label: 'Clients retenues de garantie', type: 'actif', system: 'ohada' },
    { code: '412', label: 'Clients effets à recevoir', type: 'actif', system: 'ohada' },
    { code: '416', label: 'Créances clients litigieuses ou douteuses', type: 'actif', system: 'ohada' },
    { code: '4161', label: 'Créances litigieuses', type: 'actif', system: 'ohada' },
    { code: '4162', label: 'Créances douteuses', type: 'actif', system: 'ohada' },
    { code: '418', label: 'Clients produits à recevoir', type: 'actif', system: 'ohada' },
    { code: '4181', label: 'Clients factures à établir', type: 'actif', system: 'ohada' },
    { code: '419', label: 'Clients créditeurs avances reçues', type: 'passif', system: 'ohada' },
    { code: '4191', label: 'Clients avances et acomptes reçus', type: 'passif', system: 'ohada' },
    { code: '4198', label: 'Rabais remises ristournes à accorder', type: 'passif', system: 'ohada' },
    { code: '421', label: 'Personnel avances et acomptes', type: 'actif', system: 'ohada' },
    { code: '4211', label: 'Personnel avances', type: 'actif', system: 'ohada' },
    { code: '4212', label: 'Personnel acomptes', type: 'actif', system: 'ohada' },
    { code: '422', label: 'Personnel rémunérations dues', type: 'passif', system: 'ohada' },
    { code: '423', label: 'Personnel oppositions et saisies-arrêts', type: 'passif', system: 'ohada' },
    { code: '424', label: 'Personnel oeuvres sociales internes', type: 'passif', system: 'ohada' },
    { code: '4241', label: 'Assistance médicale', type: 'passif', system: 'ohada' },
    { code: '4242', label: 'Allocations familiales', type: 'passif', system: 'ohada' },
    { code: '425', label: 'Représentants du personnel', type: 'passif', system: 'ohada' },
    { code: '426', label: 'Personnel participation aux bénéfices', type: 'passif', system: 'ohada' },
    { code: '427', label: 'Personnel dépôts', type: 'passif', system: 'ohada' },
    { code: '428', label: 'Personnel charges à payer', type: 'passif', system: 'ohada' },
    { code: '4281', label: 'Dettes provisionnées congés à payer', type: 'passif', system: 'ohada' },
    { code: '4286', label: 'Autres charges à payer personnel', type: 'passif', system: 'ohada' },
    { code: '431', label: 'Sécurité sociale CNSS', type: 'passif', system: 'ohada' },
    { code: '4311', label: 'Prestations familiales', type: 'passif', system: 'ohada' },
    { code: '4312', label: 'Accidents de travail', type: 'passif', system: 'ohada' },
    { code: '4313', label: 'Caisse de retraite obligatoire', type: 'passif', system: 'ohada' },
    { code: '4314', label: 'Caisse de retraite facultative', type: 'passif', system: 'ohada' },
    { code: '4318', label: 'Autres cotisations sociales', type: 'passif', system: 'ohada' },
    { code: '432', label: 'Caisses de retraite complémentaire', type: 'passif', system: 'ohada' },
    { code: '433', label: 'Autres organismes sociaux', type: 'passif', system: 'ohada' },
    { code: '4331', label: 'Mutuelle', type: 'passif', system: 'ohada' },
    { code: '438', label: 'Organismes sociaux charges à payer', type: 'passif', system: 'ohada' },
    { code: '4381', label: 'Charges sociales sur gratifications', type: 'passif', system: 'ohada' },
    { code: '4382', label: 'Charges sociales sur congés à payer', type: 'passif', system: 'ohada' },
    { code: '441', label: "État impôt sur les bénéfices", type: 'passif', system: 'ohada' },
    { code: '442', label: 'État autres impôts et taxes', type: 'passif', system: 'ohada' },
    { code: '4421', label: "Impôts et taxes d'État", type: 'passif', system: 'ohada' },
    { code: '4422', label: 'Impôts et taxes collectivités publiques', type: 'passif', system: 'ohada' },
    { code: '4426', label: 'Droits de douane', type: 'passif', system: 'ohada' },
    { code: '4428', label: 'Autres impôts et taxes', type: 'passif', system: 'ohada' },
    { code: '443', label: 'État TVA facturée', type: 'passif', system: 'ohada' },
    { code: '4431', label: 'TVA facturée sur ventes', type: 'passif', system: 'ohada' },
    { code: '4432', label: 'TVA facturée sur prestations de services', type: 'passif', system: 'ohada' },
    { code: '4433', label: 'TVA facturée sur travaux', type: 'passif', system: 'ohada' },
    { code: '444', label: 'État TVA due ou crédit de TVA', type: 'passif', system: 'ohada' },
    { code: '4441', label: 'État TVA due', type: 'passif', system: 'ohada' },
    { code: '4449', label: 'État crédit de TVA à reporter', type: 'actif', system: 'ohada' },
    { code: '445', label: 'État TVA récupérable', type: 'actif', system: 'ohada' },
    { code: '4451', label: 'TVA récupérable sur immobilisations', type: 'actif', system: 'ohada' },
    { code: '4452', label: 'TVA récupérable sur achats', type: 'actif', system: 'ohada' },
    { code: '4453', label: 'TVA récupérable sur transport', type: 'actif', system: 'ohada' },
    { code: '4454', label: 'TVA récupérable sur services extérieurs', type: 'actif', system: 'ohada' },
    { code: '447', label: 'État impôts retenus à la source', type: 'passif', system: 'ohada' },
    { code: '4471', label: 'Impôt Général sur le Revenu IGR', type: 'passif', system: 'ohada' },
    { code: '4472', label: 'Impôts sur salaires', type: 'passif', system: 'ohada' },
    { code: '4473', label: 'Contribution nationale', type: 'passif', system: 'ohada' },
    { code: '447201', label: 'IMPOT IRPP', type: 'passif', system: 'ohada' },
    { code: '447202', label: 'IMPOT TCS', type: 'passif', system: 'ohada' },
    { code: '447203', label: 'IMPOT FNH', type: 'passif', system: 'ohada' },
    { code: '447204', label: 'IMPOT CFP', type: 'passif', system: 'ohada' },
    { code: '4474', label: 'CONTRIBUTION SPECIAL DE SOLIDARITE', type: 'passif', system: 'ohada' },
    { code: '447800', label: 'TPS 9.5% IRPP', type: 'passif', system: 'ohada' },
    { code: '447820', label: 'TSIL 15%', type: 'passif', system: 'ohada' },
    { code: '448', label: 'État charges à payer et produits à recevoir', type: 'passif', system: 'ohada' },
    { code: '44820', label: 'Charges fiscales sur congés à payer', type: 'passif', system: 'ohada' },
    { code: '4486', label: 'Charges à payer État', type: 'passif', system: 'ohada' },
    { code: '4487', label: 'Produits à recevoir État', type: 'actif', system: 'ohada' },
    { code: '449', label: 'État créances et dettes diverses', type: 'passif', system: 'ohada' },
    { code: '4492', label: 'État avances et acomptes versés sur impôts', type: 'actif', system: 'ohada' },
    { code: '4494', label: "État subventions d'équipement à recevoir", type: 'actif', system: 'ohada' },
    { code: '461', label: 'Associés opérations sur le capital', type: 'passif', system: 'ohada' },
    { code: '4611', label: 'Associés apports en nature', type: 'actif', system: 'ohada' },
    { code: '4612', label: 'Associés apports en numéraire', type: 'actif', system: 'ohada' },
    { code: '462', label: 'Associés comptes courants', type: 'passif', system: 'ohada' },
    { code: '46210', label: 'OPTIKAH', type: 'passif', system: 'ohada' },
    { code: '462110', label: 'OLYMPIO', type: 'passif', system: 'ohada' },
    { code: '462111', label: 'DUBOZE SABINE RICHARD', type: 'passif', system: 'ohada' },
    { code: '46211', label: 'DOUMBA', type: 'passif', system: 'ohada' },
    { code: '465', label: 'Associés dividendes à payer', type: 'passif', system: 'ohada' },
    { code: '466', label: 'Groupe comptes courants', type: 'passif', system: 'ohada' },
    { code: '471', label: 'Débiteurs divers', type: 'actif', system: 'ohada' },
    { code: '4711', label: 'Débiteurs divers détail', type: 'actif', system: 'ohada' },
    { code: '4712', label: 'Créditeurs divers', type: 'passif', system: 'ohada' },
    { code: '476', label: "Charges constatées d'avance", type: 'actif', system: 'ohada' },
    { code: '477', label: "Produits constatés d'avance", type: 'passif', system: 'ohada' },
    { code: '478', label: 'Écarts de conversion actif', type: 'actif', system: 'ohada' },
    { code: '479', label: 'Écarts de conversion passif', type: 'passif', system: 'ohada' },
    { code: '481', label: "Fournisseurs d'investissements", type: 'passif', system: 'ohada' },
    { code: '4811', label: 'Fournisseurs immobilisations incorporelles', type: 'passif', system: 'ohada' },
    { code: '4812', label: 'Fournisseurs immobilisations corporelles', type: 'passif', system: 'ohada' },
    { code: '48120', label: 'FOURNISSEUR IMMOBILISATIONS CORPORELLES', type: 'passif', system: 'ohada' },
    { code: '482', label: "Fournisseurs d'investissements effets à payer", type: 'passif', system: 'ohada' },
    { code: '484', label: 'Autres dettes HAO', type: 'passif', system: 'ohada' },
    { code: '485', label: "Créances sur cessions d'immobilisations", type: 'actif', system: 'ohada' },
    { code: '488', label: 'Autres créances HAO', type: 'actif', system: 'ohada' },
    { code: '491', label: 'Dépréciations des comptes clients', type: 'actif', system: 'ohada' },
    { code: '4911', label: 'Dépréciations créances litigieuses', type: 'actif', system: 'ohada' },
    { code: '4912', label: 'Dépréciations créances douteuses', type: 'actif', system: 'ohada' },
    { code: '49100', label: 'Dépréc. Comptes de clients', type: 'actif', system: 'ohada' },
    { code: '492', label: 'Dépréciations comptes personnel', type: 'actif', system: 'ohada' },
    { code: '494', label: "Dépréciations comptes État", type: 'actif', system: 'ohada' },
    { code: '497', label: 'Dépréciations comptes débiteurs divers', type: 'actif', system: 'ohada' },
    { code: '499', label: 'Risques provisionnés', type: 'passif', system: 'ohada' },
    // ══ OHADA CLASSE 5 ══
    { code: '501', label: 'Titres du trésor et bons de caisse', type: 'tresorerie', system: 'ohada' },
    { code: '502', label: 'Actions placement', type: 'tresorerie', system: 'ohada' },
    { code: '503', label: 'Obligations placement', type: 'tresorerie', system: 'ohada' },
    { code: '511', label: 'Effets à encaisser', type: 'tresorerie', system: 'ohada' },
    { code: '513', label: 'Chèques à encaisser', type: 'tresorerie', system: 'ohada' },
    { code: '515', label: 'Cartes de crédit à encaisser', type: 'tresorerie', system: 'ohada' },
    { code: '521', label: 'Banques locales', type: 'tresorerie', system: 'ohada' },
    { code: '5211', label: 'Banque principale', type: 'tresorerie', system: 'ohada' },
    { code: '5212', label: 'Banque secondaire', type: 'tresorerie', system: 'ohada' },
    { code: '52110', label: 'Banque UBA', type: 'tresorerie', system: 'ohada' },
    { code: '52111', label: 'Banque BGFIBank', type: 'tresorerie', system: 'ohada' },
    { code: '52112', label: 'Banque BICIG', type: 'tresorerie', system: 'ohada' },
    { code: '52113', label: 'Banque Orabank', type: 'tresorerie', system: 'ohada' },
    { code: '521002', label: 'Banque UBA compte courant', type: 'tresorerie', system: 'ohada' },
    { code: '522', label: "Banques autres États région", type: 'tresorerie', system: 'ohada' },
    { code: '524', label: 'Banques hors zone monétaire', type: 'tresorerie', system: 'ohada' },
    { code: '531', label: 'Chèques postaux', type: 'tresorerie', system: 'ohada' },
    { code: '532', label: 'Trésor', type: 'tresorerie', system: 'ohada' },
    { code: '538', label: 'Autres organismes financiers', type: 'tresorerie', system: 'ohada' },
    { code: '561', label: 'Crédits de trésorerie banque', type: 'passif', system: 'ohada' },
    { code: '571', label: 'Caisse siège social', type: 'tresorerie', system: 'ohada' },
    { code: '5711', label: 'Caisse en monnaie locale', type: 'tresorerie', system: 'ohada' },
    { code: '5712', label: 'Caisse en devises', type: 'tresorerie', system: 'ohada' },
    { code: '572', label: 'Caisse succursale A', type: 'tresorerie', system: 'ohada' },
    { code: '573', label: 'Caisse succursale B', type: 'tresorerie', system: 'ohada' },
    { code: '581', label: "Régies d'avance", type: 'tresorerie', system: 'ohada' },
    { code: '585', label: 'Virements de fonds', type: 'tresorerie', system: 'ohada' },
    { code: '590', label: 'Dépréciations des titres de placement', type: 'actif', system: 'ohada' },
    { code: '5990', label: 'Provision pour risque à court terme', type: 'passif', system: 'ohada' },
    { code: '599', label: 'Risques provisionnés à caractère financier', type: 'passif', system: 'ohada' },
    // ══ OHADA CLASSE 6 ══
    { code: '601', label: 'Achats de marchandises', type: 'charge', system: 'ohada' },
    { code: '6011', label: 'Achats de marchandises dans la Région', type: 'charge', system: 'ohada' },
    { code: '602', label: 'Achats de matières premières et fournitures', type: 'charge', system: 'ohada' },
    { code: '6021', label: 'Achats matières premières dans la Région', type: 'charge', system: 'ohada' },
    { code: '603', label: 'Variations des stocks de biens achetés', type: 'charge', system: 'ohada' },
    { code: '604', label: 'Achats stockés matières et fournitures consommables', type: 'charge', system: 'ohada' },
    { code: '6041', label: 'Matières consommables', type: 'charge', system: 'ohada' },
    { code: '6042', label: 'Matières combustibles', type: 'charge', system: 'ohada' },
    { code: '6044', label: "Fournitures d'atelier et d'usine", type: 'charge', system: 'ohada' },
    { code: '6047', label: 'Fournitures de bureau', type: 'charge', system: 'ohada' },
    { code: '605', label: 'Autres achats', type: 'charge', system: 'ohada' },
    { code: '6051', label: 'Fournitures non stockables Eau', type: 'charge', system: 'ohada' },
    { code: '6052', label: 'Fournitures non stockables Électricité', type: 'charge', system: 'ohada' },
    { code: '6053', label: 'Autres énergies', type: 'charge', system: 'ohada' },
    { code: '6055', label: 'Fournitures de bureau non stockables', type: 'charge', system: 'ohada' },
    { code: '611', label: 'Transports sur achats', type: 'charge', system: 'ohada' },
    { code: '612', label: 'Transports sur ventes', type: 'charge', system: 'ohada' },
    { code: '614', label: 'Transports du personnel', type: 'charge', system: 'ohada' },
    { code: '618', label: 'Autres frais de transport', type: 'charge', system: 'ohada' },
    { code: '6181', label: 'Voyages et déplacements', type: 'charge', system: 'ohada' },
    { code: '621', label: 'Sous-traitance générale', type: 'charge', system: 'ohada' },
    { code: '622', label: 'Locations et charges locatives', type: 'charge', system: 'ohada' },
    { code: '6221', label: 'Locations de terrains', type: 'charge', system: 'ohada' },
    { code: '6222', label: 'Locations de bâtiments', type: 'charge', system: 'ohada' },
    { code: '623', label: 'Redevances de crédit-bail', type: 'charge', system: 'ohada' },
    { code: '624', label: 'Entretien réparations et maintenance', type: 'charge', system: 'ohada' },
    { code: '6241', label: 'Entretien et réparations biens immobiliers', type: 'charge', system: 'ohada' },
    { code: '6242', label: 'Entretien et réparations biens mobiliers', type: 'charge', system: 'ohada' },
    { code: '6243', label: 'Maintenance', type: 'charge', system: 'ohada' },
    { code: '625', label: "Primes d'assurance", type: 'charge', system: 'ohada' },
    { code: '6251', label: 'Assurances multirisques', type: 'charge', system: 'ohada' },
    { code: '626', label: 'Études recherches et documentation', type: 'charge', system: 'ohada' },
    { code: '627', label: 'Publicité publications relations publiques', type: 'charge', system: 'ohada' },
    { code: '6271', label: 'Annonces et insertions', type: 'charge', system: 'ohada' },
    { code: '628', label: 'Frais de télécommunications', type: 'charge', system: 'ohada' },
    { code: '6281', label: 'Frais de téléphone', type: 'charge', system: 'ohada' },
    { code: '631', label: 'Frais bancaires', type: 'charge', system: 'ohada' },
    { code: '6311', label: 'Frais sur titres', type: 'charge', system: 'ohada' },
    { code: '632', label: "Rémunérations d'intermédiaires et de conseils", type: 'charge', system: 'ohada' },
    { code: '6321', label: 'Commissions et courtages sur achats', type: 'charge', system: 'ohada' },
    { code: '6324', label: 'Honoraires', type: 'charge', system: 'ohada' },
    { code: '6325', label: "Frais d'actes et de contentieux", type: 'charge', system: 'ohada' },
    { code: '633', label: 'Frais de formation du personnel', type: 'charge', system: 'ohada' },
    { code: '634', label: 'Redevances pour brevets licences logiciels', type: 'charge', system: 'ohada' },
    { code: '635', label: 'Cotisations', type: 'charge', system: 'ohada' },
    { code: '637', label: 'Rémunérations de personnel extérieur', type: 'charge', system: 'ohada' },
    { code: '638', label: 'Autres charges externes', type: 'charge', system: 'ohada' },
    { code: '641', label: 'Impôts et taxes directs', type: 'charge', system: 'ohada' },
    { code: '6411', label: 'Impôts fonciers et taxes annexes', type: 'charge', system: 'ohada' },
    { code: '6412', label: 'Patentes licences et taxes annexes', type: 'charge', system: 'ohada' },
    { code: '6413', label: 'Taxes sur appointements et salaires', type: 'charge', system: 'ohada' },
    { code: '645', label: 'Impôts et taxes indirects', type: 'charge', system: 'ohada' },
    { code: '646', label: "Droits d'enregistrement", type: 'charge', system: 'ohada' },
    { code: '647', label: 'Pénalités et amendes fiscales', type: 'charge', system: 'ohada' },
    { code: '648', label: 'Autres impôts et taxes', type: 'charge', system: 'ohada' },
    { code: '651', label: 'Pertes sur créances clients', type: 'charge', system: 'ohada' },
    { code: '658', label: 'Charges diverses', type: 'charge', system: 'ohada' },
    { code: '6581', label: 'Jetons de présence et rémunérations administrateurs', type: 'charge', system: 'ohada' },
    { code: '659', label: "Charges provisionnées d'exploitation", type: 'charge', system: 'ohada' },
    { code: '661', label: 'Rémunérations directes personnel national', type: 'charge', system: 'ohada' },
    { code: '6611', label: 'Appointements salaires et commissions', type: 'charge', system: 'ohada' },
    { code: '6612', label: 'Primes et gratifications', type: 'charge', system: 'ohada' },
    { code: '6613', label: 'Congés payés', type: 'charge', system: 'ohada' },
    { code: '6614', label: 'Indemnités de préavis et licenciement', type: 'charge', system: 'ohada' },
    { code: '6615', label: 'Indemnités de maladie', type: 'charge', system: 'ohada' },
    { code: '6617', label: 'Avantages en nature', type: 'charge', system: 'ohada' },
    { code: '662', label: 'Rémunérations directes personnel non national', type: 'charge', system: 'ohada' },
    { code: '663', label: 'Indemnités forfaitaires versées au personnel', type: 'charge', system: 'ohada' },
    { code: '6631', label: 'Indemnités de logement', type: 'charge', system: 'ohada' },
    { code: '6632', label: 'Indemnités de représentation', type: 'charge', system: 'ohada' },
    { code: '664', label: 'Charges sociales', type: 'charge', system: 'ohada' },
    { code: '6641', label: 'Charges sociales personnel national', type: 'charge', system: 'ohada' },
    { code: '668', label: 'Autres charges sociales', type: 'charge', system: 'ohada' },
    { code: '671', label: 'Intérêts des emprunts', type: 'charge', system: 'ohada' },
    { code: '6711', label: 'Intérêts des emprunts obligataires', type: 'charge', system: 'ohada' },
    { code: '6712', label: "Intérêts des emprunts établissements de crédit", type: 'charge', system: 'ohada' },
    { code: '673', label: 'Escomptes accordés', type: 'charge', system: 'ohada' },
    { code: '676', label: 'Pertes de change', type: 'charge', system: 'ohada' },
    { code: '679', label: 'Charges provisionnées financières', type: 'charge', system: 'ohada' },
    { code: '681', label: "Dotations aux amortissements d'exploitation", type: 'charge', system: 'ohada' },
    { code: '6811', label: 'Dotations amort. charges immobilisées', type: 'charge', system: 'ohada' },
    { code: '6812', label: 'Dotations amort. immobilisations incorporelles', type: 'charge', system: 'ohada' },
    { code: '6813', label: 'Dotations amort. immobilisations corporelles', type: 'charge', system: 'ohada' },
    { code: '687', label: 'Dotations aux amortissements financiers', type: 'charge', system: 'ohada' },
    { code: '691', label: "Dotations aux provisions d'exploitation", type: 'charge', system: 'ohada' },
    { code: '6911', label: 'Dotations provisions risques et charges', type: 'charge', system: 'ohada' },
    { code: '6913', label: 'Dotations dépréciations immo. incorporelles', type: 'charge', system: 'ohada' },
    { code: '6914', label: 'Dotations dépréciations immo. corporelles', type: 'charge', system: 'ohada' },
    { code: '697', label: 'Dotations aux provisions financières', type: 'charge', system: 'ohada' },
    // ══ OHADA CLASSE 7 ══
    { code: '701', label: 'Ventes de marchandises', type: 'produit', system: 'ohada' },
    { code: '7011', label: 'Ventes de marchandises dans la Région', type: 'produit', system: 'ohada' },
    { code: '7012', label: 'Ventes de marchandises hors Région', type: 'produit', system: 'ohada' },
    { code: '702', label: 'Ventes de produits finis', type: 'produit', system: 'ohada' },
    { code: '703', label: 'Ventes de produits intermédiaires', type: 'produit', system: 'ohada' },
    { code: '704', label: 'Ventes de produits résiduels', type: 'produit', system: 'ohada' },
    { code: '705', label: 'Travaux facturés', type: 'produit', system: 'ohada' },
    { code: '7051', label: 'Travaux facturés dans la Région', type: 'produit', system: 'ohada' },
    { code: '706', label: 'Services vendus', type: 'produit', system: 'ohada' },
    { code: '7061', label: 'Services vendus dans la Région', type: 'produit', system: 'ohada' },
    { code: '7062', label: 'Services vendus hors Région', type: 'produit', system: 'ohada' },
    { code: '707', label: 'Produits accessoires', type: 'produit', system: 'ohada' },
    { code: '711', label: "Subventions sur produits à l'exportation", type: 'produit', system: 'ohada' },
    { code: '718', label: "Autres subventions d'exploitation", type: 'produit', system: 'ohada' },
    { code: '7181', label: "Subventions État et collectivités publiques", type: 'produit', system: 'ohada' },
    { code: '721', label: 'Production immobilisée incorporelle', type: 'produit', system: 'ohada' },
    { code: '722', label: 'Production immobilisée corporelle', type: 'produit', system: 'ohada' },
    { code: '734', label: 'Variations des stocks de produits en cours', type: 'produit', system: 'ohada' },
    { code: '736', label: 'Variations des stocks de produits finis', type: 'produit', system: 'ohada' },
    { code: '752', label: "Quote-part résultats opérations en commun", type: 'produit', system: 'ohada' },
    { code: '754', label: "Produits des cessions courantes d'immo.", type: 'produit', system: 'ohada' },
    { code: '758', label: 'Produits divers', type: 'produit', system: 'ohada' },
    { code: '759', label: "Reprises charges provisionnées d'exploitation", type: 'produit', system: 'ohada' },
    { code: '771', label: 'Intérêts de prêts', type: 'produit', system: 'ohada' },
    { code: '772', label: 'Revenus de participations', type: 'produit', system: 'ohada' },
    { code: '773', label: 'Escomptes obtenus', type: 'produit', system: 'ohada' },
    { code: '774', label: 'Revenus de titres de placement', type: 'produit', system: 'ohada' },
    { code: '776', label: 'Gains de change', type: 'produit', system: 'ohada' },
    { code: '779', label: 'Reprises charges provisionnées financières', type: 'produit', system: 'ohada' },
    { code: '781', label: "Transferts de charges d'exploitation", type: 'produit', system: 'ohada' },
    { code: '791', label: "Reprises de provisions d'exploitation", type: 'produit', system: 'ohada' },
    { code: '797', label: 'Reprises de provisions financières', type: 'produit', system: 'ohada' },
    // ══ OHADA CLASSE 8 ══
    { code: '811', label: 'Cessions immobilisations incorporelles', type: 'charge', system: 'ohada' },
    { code: '812', label: 'Cessions immobilisations corporelles', type: 'charge', system: 'ohada' },
    { code: '816', label: 'Cessions immobilisations financières', type: 'charge', system: 'ohada' },
    { code: '821', label: 'Produits cessions immo. incorporelles', type: 'produit', system: 'ohada' },
    { code: '822', label: 'Produits cessions immo. corporelles', type: 'produit', system: 'ohada' },
    { code: '826', label: 'Produits cessions immo. financières', type: 'produit', system: 'ohada' },
    { code: '831', label: 'Charges HAO constatées', type: 'charge', system: 'ohada' },
    { code: '834', label: 'Pertes sur créances HAO', type: 'charge', system: 'ohada' },
    { code: '835', label: 'Dons et libéralités accordés', type: 'charge', system: 'ohada' },
    { code: '836', label: 'Abandons de créances consentis', type: 'charge', system: 'ohada' },
    { code: '841', label: 'Produits HAO constatés', type: 'produit', system: 'ohada' },
    { code: '845', label: 'Dons et libéralités obtenus', type: 'produit', system: 'ohada' },
    { code: '848', label: 'Transferts de charges HAO', type: 'produit', system: 'ohada' },
    { code: '851', label: 'Dotations aux provisions réglementées', type: 'charge', system: 'ohada' },
    { code: '852', label: 'Dotations aux amortissements HAO', type: 'charge', system: 'ohada' },
    { code: '861', label: 'Reprises de provisions réglementées', type: 'produit', system: 'ohada' },
    { code: '862', label: "Reprises d'amortissements", type: 'produit', system: 'ohada' },
    { code: '865', label: "Reprises de subventions d'investissement", type: 'produit', system: 'ohada' },
    { code: '871', label: 'Participation légale aux bénéfices', type: 'charge', system: 'ohada' },
    { code: '881', label: "Subventions d'équilibre État", type: 'produit', system: 'ohada' },
    { code: '891', label: "Impôts sur les bénéfices de l'exercice", type: 'charge', system: 'ohada' },
    { code: '895', label: 'Impôt minimum forfaitaire IMF', type: 'charge', system: 'ohada' },
    { code: '899', label: "Dégrèvements et annulations d'impôts antérieurs", type: 'produit', system: 'ohada' },
    // ══ PCG FRANCE CLASSE 1 ══
    { code: '101', label: 'Capital', type: 'passif', system: 'pcg_france' },
    { code: '1011', label: 'Capital souscrit non appelé', type: 'passif', system: 'pcg_france' },
    { code: '1012', label: 'Capital souscrit appelé non versé', type: 'passif', system: 'pcg_france' },
    { code: '1013', label: 'Capital souscrit appelé versé', type: 'passif', system: 'pcg_france' },
    { code: '104', label: 'Primes liées au capital', type: 'passif', system: 'pcg_france' },
    { code: '1041', label: "Primes d'émission", type: 'passif', system: 'pcg_france' },
    { code: '1042', label: 'Primes de fusion', type: 'passif', system: 'pcg_france' },
    { code: '1043', label: "Primes d'apport", type: 'passif', system: 'pcg_france' },
    { code: '105', label: 'Écarts de réévaluation', type: 'passif', system: 'pcg_france' },
    { code: '106', label: 'Réserves', type: 'passif', system: 'pcg_france' },
    { code: '1061', label: 'Réserve légale', type: 'passif', system: 'pcg_france' },
    { code: '1062', label: 'Réserves indisponibles', type: 'passif', system: 'pcg_france' },
    { code: '1063', label: 'Réserves statutaires ou contractuelles', type: 'passif', system: 'pcg_france' },
    { code: '1064', label: 'Réserves réglementées', type: 'passif', system: 'pcg_france' },
    { code: '1068', label: 'Autres réserves', type: 'passif', system: 'pcg_france' },
    { code: '108', label: "Compte de l'exploitant", type: 'passif', system: 'pcg_france' },
    { code: '110', label: 'Report à nouveau solde créditeur', type: 'passif', system: 'pcg_france' },
    { code: '119', label: 'Report à nouveau solde débiteur', type: 'passif', system: 'pcg_france' },
    { code: '120', label: "Résultat de l'exercice bénéfice", type: 'passif', system: 'pcg_france' },
    { code: '129', label: "Résultat de l'exercice perte", type: 'passif', system: 'pcg_france' },
    { code: '131', label: "Subventions d'investissement octroyées", type: 'passif', system: 'pcg_france' },
    { code: '143', label: 'Provisions réglementées pour hausse de prix', type: 'passif', system: 'pcg_france' },
    { code: '145', label: 'Amortissements dérogatoires', type: 'passif', system: 'pcg_france' },
    { code: '151', label: 'Provisions pour risques', type: 'passif', system: 'pcg_france' },
    { code: '1511', label: 'Provisions pour litiges', type: 'passif', system: 'pcg_france' },
    { code: '1512', label: 'Provisions pour garanties données aux clients', type: 'passif', system: 'pcg_france' },
    { code: '1514', label: 'Provisions pour amendes et pénalités', type: 'passif', system: 'pcg_france' },
    { code: '1515', label: 'Provisions pour pertes de change', type: 'passif', system: 'pcg_france' },
    { code: '1518', label: 'Autres provisions pour risques', type: 'passif', system: 'pcg_france' },
    { code: '152', label: 'Provisions pour charges', type: 'passif', system: 'pcg_france' },
    { code: '1521', label: 'Provisions pour pensions et obligations similaires', type: 'passif', system: 'pcg_france' },
    { code: '1522', label: 'Provisions pour restructurations', type: 'passif', system: 'pcg_france' },
    { code: '1523', label: 'Provisions pour impôts', type: 'passif', system: 'pcg_france' },
    { code: '1525', label: 'Provisions pour gros entretien', type: 'passif', system: 'pcg_france' },
    { code: '161', label: 'Emprunts obligataires convertibles', type: 'passif', system: 'pcg_france' },
    { code: '163', label: 'Autres emprunts obligataires', type: 'passif', system: 'pcg_france' },
    { code: '164', label: "Emprunts auprès des établissements de crédit", type: 'passif', system: 'pcg_france' },
    { code: '1648', label: "Intérêts courus emprunts établissements de crédit", type: 'passif', system: 'pcg_france' },
    { code: '165', label: 'Dépôts et cautionnements reçus', type: 'passif', system: 'pcg_france' },
    { code: '166', label: 'Participation des salariés aux résultats', type: 'passif', system: 'pcg_france' },
    { code: '168', label: 'Autres emprunts et dettes assimilées', type: 'passif', system: 'pcg_france' },
    { code: '1681', label: 'Autres emprunts PCG', type: 'passif', system: 'pcg_france' },
    { code: '1682', label: 'Emprunts participatifs PCG', type: 'passif', system: 'pcg_france' },
    { code: '1688', label: 'Intérêts courus autres emprunts PCG', type: 'passif', system: 'pcg_france' },
    { code: '169', label: 'Primes de remboursement des emprunts', type: 'passif', system: 'pcg_france' },
    { code: '171', label: 'Dettes rattachées participations groupe', type: 'passif', system: 'pcg_france' },
    { code: '174', label: 'Dettes rattachées participations hors groupe', type: 'passif', system: 'pcg_france' },
    // ══ PCG CLASSE 2 ══
    { code: '201', label: "Frais d'établissement PCG", type: 'actif', system: 'pcg_france' },
    { code: '2011', label: 'Frais de constitution PCG', type: 'actif', system: 'pcg_france' },
    { code: '203', label: 'Frais de développement', type: 'actif', system: 'pcg_france' },
    { code: '205', label: 'Concessions brevets licences marques logiciels', type: 'actif', system: 'pcg_france' },
    { code: '206', label: 'Droit au bail PCG', type: 'actif', system: 'pcg_france' },
    { code: '207', label: 'Fonds commercial PCG', type: 'actif', system: 'pcg_france' },
    { code: '208', label: 'Autres immobilisations incorporelles PCG', type: 'actif', system: 'pcg_france' },
    { code: '211', label: 'Terrains PCG', type: 'actif', system: 'pcg_france' },
    { code: '2111', label: 'Terrains nus PCG', type: 'actif', system: 'pcg_france' },
    { code: '2112', label: 'Terrains aménagés PCG', type: 'actif', system: 'pcg_france' },
    { code: '2115', label: 'Terrains bâtis PCG', type: 'actif', system: 'pcg_france' },
    { code: '212', label: 'Agencements et aménagements de terrains', type: 'actif', system: 'pcg_france' },
    { code: '213', label: 'Constructions PCG', type: 'actif', system: 'pcg_france' },
    { code: '2131', label: 'Bâtiments PCG', type: 'actif', system: 'pcg_france' },
    { code: '2135', label: 'Installations générales agencements constructions', type: 'actif', system: 'pcg_france' },
    { code: '214', label: "Constructions sur sol d'autrui PCG", type: 'actif', system: 'pcg_france' },
    { code: '215', label: 'Installations techniques matériels et outillages', type: 'actif', system: 'pcg_france' },
    { code: '2151', label: 'Installations complexes spécialisées PCG', type: 'actif', system: 'pcg_france' },
    { code: '2154', label: 'Matériels industriels PCG', type: 'actif', system: 'pcg_france' },
    { code: '2155', label: 'Outillages industriels PCG', type: 'actif', system: 'pcg_france' },
    { code: '218', label: 'Autres immobilisations corporelles PCG', type: 'actif', system: 'pcg_france' },
    { code: '2181', label: 'Installations générales agencements divers PCG', type: 'actif', system: 'pcg_france' },
    { code: '2182', label: 'Matériel de transport PCG', type: 'actif', system: 'pcg_france' },
    { code: '2183', label: 'Matériel de bureau et matériel informatique PCG', type: 'actif', system: 'pcg_france' },
    { code: '2184', label: 'Mobilier PCG', type: 'actif', system: 'pcg_france' },
    { code: '231', label: 'Immobilisations corporelles en cours PCG', type: 'actif', system: 'pcg_france' },
    { code: '232', label: 'Immobilisations incorporelles en cours PCG', type: 'actif', system: 'pcg_france' },
    { code: '237', label: 'Avances sur commandes immo. incorporelles PCG', type: 'actif', system: 'pcg_france' },
    { code: '238', label: 'Avances sur commandes immo. corporelles PCG', type: 'actif', system: 'pcg_france' },
    { code: '261', label: 'Titres de participation PCG', type: 'actif', system: 'pcg_france' },
    { code: '2611', label: 'Actions titres de participation PCG', type: 'actif', system: 'pcg_france' },
    { code: '262', label: 'Titres évalués par équivalence', type: 'actif', system: 'pcg_france' },
    { code: '266', label: 'Autres formes de participation PCG', type: 'actif', system: 'pcg_france' },
    { code: '267', label: 'Créances rattachées à des participations PCG', type: 'actif', system: 'pcg_france' },
    { code: '2671', label: 'Créances rattachées participations groupe PCG', type: 'actif', system: 'pcg_france' },
    { code: '271', label: 'Titres immobilisés droit de propriété PCG', type: 'actif', system: 'pcg_france' },
    { code: '2711', label: 'Actions titres immobilisés PCG', type: 'actif', system: 'pcg_france' },
    { code: '272', label: 'Titres immobilisés droit de créance PCG', type: 'actif', system: 'pcg_france' },
    { code: '274', label: 'Prêts PCG', type: 'actif', system: 'pcg_france' },
    { code: '2741', label: 'Prêts participatifs PCG', type: 'actif', system: 'pcg_france' },
    { code: '2742', label: 'Prêts aux associés PCG', type: 'actif', system: 'pcg_france' },
    { code: '2743', label: 'Prêts au personnel PCG', type: 'actif', system: 'pcg_france' },
    { code: '2748', label: 'Autres prêts PCG', type: 'actif', system: 'pcg_france' },
    { code: '275', label: 'Dépôts et cautionnements versés PCG', type: 'actif', system: 'pcg_france' },
    { code: '2751', label: 'Dépôts versés PCG', type: 'actif', system: 'pcg_france' },
    { code: '276', label: 'Autres créances immobilisées PCG', type: 'actif', system: 'pcg_france' },
    { code: '277', label: 'Actions propres ou parts propres', type: 'actif', system: 'pcg_france' },
    { code: '280', label: 'Amortissements immobilisations incorporelles PCG', type: 'actif', system: 'pcg_france' },
    { code: '2801', label: "Amort. frais d'établissement PCG", type: 'actif', system: 'pcg_france' },
    { code: '2803', label: 'Amort. frais de développement PCG', type: 'actif', system: 'pcg_france' },
    { code: '2805', label: 'Amort. concessions brevets licences logiciels PCG', type: 'actif', system: 'pcg_france' },
    { code: '2807', label: 'Amort. fonds commercial PCG', type: 'actif', system: 'pcg_france' },
    { code: '281', label: 'Amortissements immobilisations corporelles PCG', type: 'actif', system: 'pcg_france' },
    { code: '2812', label: 'Amort. agencements terrains PCG', type: 'actif', system: 'pcg_france' },
    { code: '2813', label: 'Amort. constructions PCG', type: 'actif', system: 'pcg_france' },
    { code: '2815', label: 'Amort. installations matériel outillage PCG', type: 'actif', system: 'pcg_france' },
    { code: '2818', label: 'Amort. autres immobilisations corporelles PCG', type: 'actif', system: 'pcg_france' },
    { code: '290', label: 'Dépréciations immobilisations incorporelles PCG', type: 'actif', system: 'pcg_france' },
    { code: '2907', label: 'Dépréciations fonds commercial PCG', type: 'actif', system: 'pcg_france' },
    { code: '291', label: 'Dépréciations immobilisations corporelles PCG', type: 'actif', system: 'pcg_france' },
    { code: '2911', label: 'Dépréciations terrains PCG', type: 'actif', system: 'pcg_france' },
    { code: '2913', label: 'Dépréciations constructions PCG', type: 'actif', system: 'pcg_france' },
    { code: '2915', label: 'Dépréciations installations techniques PCG', type: 'actif', system: 'pcg_france' },
    { code: '2918', label: 'Dépréciations autres immobilisations corporelles PCG', type: 'actif', system: 'pcg_france' },
    { code: '296', label: 'Dépréciations participations et créances PCG', type: 'actif', system: 'pcg_france' },
    { code: '2961', label: 'Dépréciations titres de participation PCG', type: 'actif', system: 'pcg_france' },
    { code: '297', label: 'Dépréciations autres immobilisations financières PCG', type: 'actif', system: 'pcg_france' },
    // ══ PCG CLASSE 3 ══
    { code: '31', label: 'Matières premières et fournitures PCG', type: 'actif', system: 'pcg_france' },
    { code: '321', label: 'Matières consommables PCG', type: 'actif', system: 'pcg_france' },
    { code: '322', label: 'Fournitures consommables PCG', type: 'actif', system: 'pcg_france' },
    { code: '3221', label: 'Combustibles PCG', type: 'actif', system: 'pcg_france' },
    { code: '3225', label: 'Fournitures de bureau PCG', type: 'actif', system: 'pcg_france' },
    { code: '326', label: 'Emballages PCG', type: 'actif', system: 'pcg_france' },
    { code: '3261', label: 'Emballages perdus PCG', type: 'actif', system: 'pcg_france' },
    { code: '331', label: 'Produits en cours PCG', type: 'actif', system: 'pcg_france' },
    { code: '335', label: 'Travaux en cours PCG', type: 'actif', system: 'pcg_france' },
    { code: '341', label: 'Études en cours PCG', type: 'actif', system: 'pcg_france' },
    { code: '345', label: 'Prestations de services en cours PCG', type: 'actif', system: 'pcg_france' },
    { code: '351', label: 'Produits intermédiaires PCG', type: 'actif', system: 'pcg_france' },
    { code: '355', label: 'Produits finis PCG', type: 'actif', system: 'pcg_france' },
    { code: '358', label: 'Produits résiduels ou matières de récupération PCG', type: 'actif', system: 'pcg_france' },
    { code: '37', label: 'Stocks de marchandises PCG', type: 'actif', system: 'pcg_france' },
    { code: '391', label: 'Dépréciations des matières premières PCG', type: 'actif', system: 'pcg_france' },
    { code: '395', label: 'Dépréciations des stocks de produits PCG', type: 'actif', system: 'pcg_france' },
    { code: '397', label: 'Dépréciations des stocks de marchandises PCG', type: 'actif', system: 'pcg_france' },
    // ══ PCG CLASSE 4 ══
    { code: '401', label: 'Fournisseurs PCG', type: 'passif', system: 'pcg_france' },
    { code: '4011', label: 'Fournisseurs achats de biens et prestations PCG', type: 'passif', system: 'pcg_france' },
    { code: '4017', label: 'Fournisseurs retenues de garantie PCG', type: 'passif', system: 'pcg_france' },
    { code: '403', label: 'Fournisseurs effets à payer PCG', type: 'passif', system: 'pcg_france' },
    { code: '404', label: "Fournisseurs d'immobilisations PCG", type: 'passif', system: 'pcg_france' },
    { code: '408', label: 'Fournisseurs factures non parvenues PCG', type: 'passif', system: 'pcg_france' },
    { code: '4081', label: 'Fournisseurs FNP exploitation PCG', type: 'passif', system: 'pcg_france' },
    { code: '4084', label: "Fournisseurs d'immobilisations FNP PCG", type: 'passif', system: 'pcg_france' },
    { code: '409', label: 'Fournisseurs débiteurs PCG', type: 'actif', system: 'pcg_france' },
    { code: '4091', label: 'Fournisseurs avances et acomptes versés PCG', type: 'actif', system: 'pcg_france' },
    { code: '4096', label: 'Fournisseurs créances emballages PCG', type: 'actif', system: 'pcg_france' },
    { code: '4098', label: 'Rabais remises ristournes à obtenir PCG', type: 'actif', system: 'pcg_france' },
    { code: '411', label: 'Clients PCG', type: 'actif', system: 'pcg_france' },
    { code: '4111', label: 'Clients ventes de biens ou prestations PCG', type: 'actif', system: 'pcg_france' },
    { code: '413', label: 'Clients effets à recevoir PCG', type: 'actif', system: 'pcg_france' },
    { code: '416', label: 'Clients douteux ou litigieux PCG', type: 'actif', system: 'pcg_france' },
    { code: '418', label: 'Clients produits non encore facturés PCG', type: 'actif', system: 'pcg_france' },
    { code: '4181', label: 'Clients factures à établir PCG', type: 'actif', system: 'pcg_france' },
    { code: '419', label: 'Clients créditeurs PCG', type: 'passif', system: 'pcg_france' },
    { code: '4191', label: 'Clients avances et acomptes reçus PCG', type: 'passif', system: 'pcg_france' },
    { code: '4198', label: 'Rabais remises ristournes à accorder PCG', type: 'passif', system: 'pcg_france' },
    { code: '421', label: 'Personnel rémunérations dues PCG', type: 'passif', system: 'pcg_france' },
    { code: '422', label: 'Comité social et économique', type: 'passif', system: 'pcg_france' },
    { code: '424', label: 'Participation des salariés aux résultats PCG', type: 'passif', system: 'pcg_france' },
    { code: '425', label: 'Personnel avances et acomptes PCG', type: 'actif', system: 'pcg_france' },
    { code: '427', label: 'Personnel oppositions PCG', type: 'passif', system: 'pcg_france' },
    { code: '428', label: 'Personnel charges à payer PCG', type: 'passif', system: 'pcg_france' },
    { code: '4282', label: 'Dettes provisionnées congés à payer PCG', type: 'passif', system: 'pcg_france' },
    { code: '431', label: 'Sécurité sociale PCG', type: 'passif', system: 'pcg_france' },
    { code: '437', label: 'Autres organismes sociaux PCG', type: 'passif', system: 'pcg_france' },
    { code: '438', label: 'Organismes sociaux charges à payer PCG', type: 'passif', system: 'pcg_france' },
    { code: '4382', label: 'Charges sociales sur congés à payer PCG', type: 'passif', system: 'pcg_france' },
    { code: '441', label: 'État subventions et aides à recevoir PCG', type: 'actif', system: 'pcg_france' },
    { code: '442', label: "Contributions impôts et taxes pour l'État PCG", type: 'passif', system: 'pcg_france' },
    { code: '444', label: 'État impôts sur les bénéfices PCG', type: 'passif', system: 'pcg_france' },
    { code: '445', label: "État taxes sur le chiffre d'affaires PCG", type: 'passif', system: 'pcg_france' },
    { code: '4452', label: 'TVA due intracommunautaire PCG', type: 'passif', system: 'pcg_france' },
    { code: '4455', label: 'Taxes sur le CA à décaisser PCG', type: 'passif', system: 'pcg_france' },
    { code: '44551', label: 'TVA à décaisser PCG', type: 'passif', system: 'pcg_france' },
    { code: '4456', label: 'Taxes sur le CA déductibles PCG', type: 'actif', system: 'pcg_france' },
    { code: '44562', label: 'TVA sur immobilisations PCG', type: 'actif', system: 'pcg_france' },
    { code: '44566', label: 'TVA sur autres biens et services PCG', type: 'actif', system: 'pcg_france' },
    { code: '44567', label: 'Crédit de TVA à reporter PCG', type: 'actif', system: 'pcg_france' },
    { code: '4457', label: 'Taxes sur le CA collectées PCG', type: 'passif', system: 'pcg_france' },
    { code: '44571', label: 'TVA collectée PCG', type: 'passif', system: 'pcg_france' },
    { code: '44583', label: 'Remboursement de TVA demandé PCG', type: 'actif', system: 'pcg_france' },
    { code: '446', label: 'Obligations cautionnées PCG', type: 'passif', system: 'pcg_france' },
    { code: '447', label: 'Autres impôts taxes et versements assimilés PCG', type: 'passif', system: 'pcg_france' },
    { code: '448', label: 'État charges à payer et produits à recevoir PCG', type: 'passif', system: 'pcg_france' },
    { code: '4481', label: 'État charges à payer PCG', type: 'passif', system: 'pcg_france' },
    { code: '44811', label: 'Charges fiscales sur congés à payer PCG', type: 'passif', system: 'pcg_france' },
    { code: '4482', label: 'État produits à recevoir PCG', type: 'actif', system: 'pcg_france' },
    { code: '451', label: 'Groupe PCG', type: 'passif', system: 'pcg_france' },
    { code: '455', label: 'Associés comptes courants PCG', type: 'passif', system: 'pcg_france' },
    { code: '4551', label: 'Principal comptes courants associés PCG', type: 'passif', system: 'pcg_france' },
    { code: '456', label: 'Associés opérations sur le capital PCG', type: 'passif', system: 'pcg_france' },
    { code: '4561', label: "Associés comptes d'apport PCG", type: 'actif', system: 'pcg_france' },
    { code: '4562', label: 'Apporteurs capital appelé non versé PCG', type: 'actif', system: 'pcg_france' },
    { code: '4563', label: 'Associés versements reçus augmentation capital PCG', type: 'passif', system: 'pcg_france' },
    { code: '4567', label: 'Associés capital à rembourser PCG', type: 'passif', system: 'pcg_france' },
    { code: '457', label: 'Associés dividendes à payer PCG', type: 'passif', system: 'pcg_france' },
    { code: '462', label: "Créances sur cessions d'immobilisations PCG", type: 'actif', system: 'pcg_france' },
    { code: '464', label: 'Dettes sur acquisitions de valeurs mobilières PCG', type: 'passif', system: 'pcg_france' },
    { code: '465', label: 'Créances sur cessions de valeurs mobilières PCG', type: 'actif', system: 'pcg_france' },
    { code: '467', label: 'Divers comptes débiteurs et produits à recevoir PCG', type: 'actif', system: 'pcg_france' },
    { code: '468', label: 'Divers comptes créditeurs et charges à payer PCG', type: 'passif', system: 'pcg_france' },
    { code: '476', label: 'Différences de conversion actif PCG', type: 'actif', system: 'pcg_france' },
    { code: '477', label: 'Différences de conversion passif PCG', type: 'passif', system: 'pcg_france' },
    { code: '481', label: "Frais d'émission des emprunts PCG", type: 'actif', system: 'pcg_france' },
    { code: '486', label: "Charges constatées d'avance PCG", type: 'actif', system: 'pcg_france' },
    { code: '487', label: "Produits constatés d'avance PCG", type: 'passif', system: 'pcg_france' },
    { code: '491', label: 'Dépréciations des comptes de clients PCG', type: 'actif', system: 'pcg_france' },
    { code: '495', label: 'Dépréciations des comptes du groupe PCG', type: 'actif', system: 'pcg_france' },
    { code: '496', label: 'Dépréciations des comptes de débiteurs divers PCG', type: 'actif', system: 'pcg_france' },
    // ══ PCG CLASSE 5 ══
    { code: '502', label: 'Actions propres PCG', type: 'tresorerie', system: 'pcg_france' },
    { code: '503', label: 'Actions PCG', type: 'tresorerie', system: 'pcg_france' },
    { code: '5031', label: 'Titres cotés PCG', type: 'tresorerie', system: 'pcg_france' },
    { code: '506', label: 'Obligations PCG', type: 'tresorerie', system: 'pcg_france' },
    { code: '507', label: 'Bons du Trésor et bons de caisse à court terme PCG', type: 'tresorerie', system: 'pcg_france' },
    { code: '508', label: 'Autres valeurs mobilières de placement PCG', type: 'tresorerie', system: 'pcg_france' },
    { code: '511', label: "Valeurs à l'encaissement PCG", type: 'tresorerie', system: 'pcg_france' },
    { code: '5112', label: 'Chèques à encaisser PCG', type: 'tresorerie', system: 'pcg_france' },
    { code: '5113', label: "Effets à l'encaissement PCG", type: 'tresorerie', system: 'pcg_france' },
    { code: '512', label: 'Banques PCG', type: 'tresorerie', system: 'pcg_france' },
    { code: '5121', label: 'Comptes en euros PCG', type: 'tresorerie', system: 'pcg_france' },
    { code: '5124', label: 'Comptes en devises PCG', type: 'tresorerie', system: 'pcg_france' },
    { code: '517', label: 'Autres organismes financiers PCG', type: 'tresorerie', system: 'pcg_france' },
    { code: '519', label: 'Concours bancaires courants PCG', type: 'passif', system: 'pcg_france' },
    { code: '53', label: 'Caisse PCG', type: 'tresorerie', system: 'pcg_france' },
    { code: '58', label: 'Virements internes PCG', type: 'tresorerie', system: 'pcg_france' },
    { code: '590', label: 'Dépréciations des VMP PCG', type: 'actif', system: 'pcg_france' },
    // ══ PCG CLASSE 6 ══
    { code: '601', label: 'Achats stockés matières premières PCG', type: 'charge', system: 'pcg_france' },
    { code: '602', label: 'Achats stockés autres approvisionnements PCG', type: 'charge', system: 'pcg_france' },
    { code: '6021', label: 'Matières consommables PCG charge', type: 'charge', system: 'pcg_france' },
    { code: '6022', label: 'Fournitures consommables PCG charge', type: 'charge', system: 'pcg_france' },
    { code: '604', label: "Achats d'études et prestations de services PCG", type: 'charge', system: 'pcg_france' },
    { code: '605', label: 'Achats de matériel équipements et travaux PCG', type: 'charge', system: 'pcg_france' },
    { code: '606', label: 'Achats non stockés de matière et fournitures PCG', type: 'charge', system: 'pcg_france' },
    { code: '6061', label: 'Fournitures non stockables eau énergie PCG', type: 'charge', system: 'pcg_france' },
    { code: '6063', label: "Fournitures d'entretien et de petit équipement PCG", type: 'charge', system: 'pcg_france' },
    { code: '6064', label: 'Fournitures administratives PCG', type: 'charge', system: 'pcg_france' },
    { code: '607', label: 'Achats de marchandises PCG', type: 'charge', system: 'pcg_france' },
    { code: '611', label: 'Sous-traitance générale PCG', type: 'charge', system: 'pcg_france' },
    { code: '612', label: 'Redevances de crédit-bail PCG', type: 'charge', system: 'pcg_france' },
    { code: '6122', label: 'Crédit-bail mobilier PCG', type: 'charge', system: 'pcg_france' },
    { code: '6125', label: 'Crédit-bail immobilier PCG', type: 'charge', system: 'pcg_france' },
    { code: '613', label: 'Locations PCG', type: 'charge', system: 'pcg_france' },
    { code: '6132', label: 'Locations immobilières PCG', type: 'charge', system: 'pcg_france' },
    { code: '6135', label: 'Locations mobilières PCG', type: 'charge', system: 'pcg_france' },
    { code: '614', label: 'Charges locatives et de copropriété PCG', type: 'charge', system: 'pcg_france' },
    { code: '615', label: 'Entretiens et réparations PCG', type: 'charge', system: 'pcg_france' },
    { code: '6152', label: 'Entretien sur biens immobiliers PCG', type: 'charge', system: 'pcg_france' },
    { code: '6155', label: 'Entretien sur biens mobiliers PCG', type: 'charge', system: 'pcg_france' },
    { code: '6156', label: 'Maintenance PCG', type: 'charge', system: 'pcg_france' },
    { code: '616', label: "Primes d'assurances PCG", type: 'charge', system: 'pcg_france' },
    { code: '6161', label: 'Multirisques PCG', type: 'charge', system: 'pcg_france' },
    { code: '617', label: 'Études et recherches PCG', type: 'charge', system: 'pcg_france' },
    { code: '621', label: "Personnel extérieur à l'entreprise PCG", type: 'charge', system: 'pcg_france' },
    { code: '6211', label: 'Personnel intérimaire PCG', type: 'charge', system: 'pcg_france' },
    { code: '622', label: "Rémunérations d'intermédiaires et honoraires PCG", type: 'charge', system: 'pcg_france' },
    { code: '6221', label: 'Commissions et courtages PCG', type: 'charge', system: 'pcg_france' },
    { code: '6226', label: 'Honoraires PCG', type: 'charge', system: 'pcg_france' },
    { code: '6227', label: "Frais d'actes et de contentieux PCG", type: 'charge', system: 'pcg_france' },
    { code: '623', label: 'Publicité publications relations publiques PCG', type: 'charge', system: 'pcg_france' },
    { code: '6231', label: 'Annonces et insertions PCG', type: 'charge', system: 'pcg_france' },
    { code: '624', label: 'Transports de biens et transports collectifs PCG', type: 'charge', system: 'pcg_france' },
    { code: '6241', label: 'Transports sur achats PCG', type: 'charge', system: 'pcg_france' },
    { code: '625', label: 'Déplacements missions et réceptions PCG', type: 'charge', system: 'pcg_france' },
    { code: '6251', label: 'Voyages et déplacements PCG', type: 'charge', system: 'pcg_france' },
    { code: '6256', label: 'Missions PCG', type: 'charge', system: 'pcg_france' },
    { code: '6257', label: 'Réceptions PCG', type: 'charge', system: 'pcg_france' },
    { code: '626', label: 'Frais postaux et de télécommunications PCG', type: 'charge', system: 'pcg_france' },
    { code: '6261', label: 'Frais postaux PCG', type: 'charge', system: 'pcg_france' },
    { code: '6262', label: 'Frais de télécommunications PCG', type: 'charge', system: 'pcg_france' },
    { code: '627', label: 'Services bancaires et assimilés PCG', type: 'charge', system: 'pcg_france' },
    { code: '6271', label: 'Frais sur titres PCG', type: 'charge', system: 'pcg_france' },
    { code: '6278', label: 'Autres frais et commissions bancaires PCG', type: 'charge', system: 'pcg_france' },
    { code: '6281', label: 'Concours divers cotisations PCG', type: 'charge', system: 'pcg_france' },
    { code: '6282', label: 'Frais de recrutement du personnel PCG', type: 'charge', system: 'pcg_france' },
    { code: '6283', label: 'Frais de formation du personnel PCG', type: 'charge', system: 'pcg_france' },
    { code: '631', label: 'Impôts et taxes sur rémunérations PCG', type: 'charge', system: 'pcg_france' },
    { code: '6311', label: 'Taxe sur les salaires PCG', type: 'charge', system: 'pcg_france' },
    { code: '6312', label: "Taxe d'apprentissage PCG", type: 'charge', system: 'pcg_france' },
    { code: '6316', label: 'Taxe sur les véhicules de société PCG', type: 'charge', system: 'pcg_france' },
    { code: '633', label: 'Impôts et taxes autres PCG', type: 'charge', system: 'pcg_france' },
    { code: '6331', label: 'Droits de mutation PCG', type: 'charge', system: 'pcg_france' },
    { code: '6336', label: 'Taxe foncière PCG', type: 'charge', system: 'pcg_france' },
    { code: '63371', label: 'Cotisation foncière des entreprises CFE', type: 'charge', system: 'pcg_france' },
    { code: '63372', label: 'Cotisation sur la valeur ajoutée CVAE', type: 'charge', system: 'pcg_france' },
    { code: '641', label: 'Rémunérations du personnel PCG', type: 'charge', system: 'pcg_france' },
    { code: '6411', label: 'Salaires et appointements PCG', type: 'charge', system: 'pcg_france' },
    { code: '6412', label: 'Congés payés PCG', type: 'charge', system: 'pcg_france' },
    { code: '6413', label: 'Primes et gratifications PCG', type: 'charge', system: 'pcg_france' },
    { code: '645', label: 'Charges de sécurité sociale et de prévoyance PCG', type: 'charge', system: 'pcg_france' },
    { code: '6451', label: "Cotisations à l'URSSAF", type: 'charge', system: 'pcg_france' },
    { code: '6452', label: 'Cotisations aux mutuelles PCG', type: 'charge', system: 'pcg_france' },
    { code: '6453', label: 'Cotisations aux caisses de retraite PCG', type: 'charge', system: 'pcg_france' },
    { code: '6454', label: 'Cotisations ASSEDIC assurance chômage', type: 'charge', system: 'pcg_france' },
    { code: '6458', label: 'Cotisations autres organismes sociaux PCG', type: 'charge', system: 'pcg_france' },
    { code: '647', label: 'Autres charges sociales PCG', type: 'charge', system: 'pcg_france' },
    { code: '6474', label: "Versements aux oeuvres sociales PCG", type: 'charge', system: 'pcg_france' },
    { code: '651', label: 'Redevances pour concessions brevets licences PCG', type: 'charge', system: 'pcg_france' },
    { code: '6516', label: 'Redevances pour brevets et licences PCG', type: 'charge', system: 'pcg_france' },
    { code: '653', label: 'Jetons de présence PCG', type: 'charge', system: 'pcg_france' },
    { code: '654', label: 'Pertes sur créances irrécouvrables PCG', type: 'charge', system: 'pcg_france' },
    { code: '658', label: 'Charges diverses de gestion courante PCG', type: 'charge', system: 'pcg_france' },
    { code: '661', label: "Charges d'intérêts PCG", type: 'charge', system: 'pcg_france' },
    { code: '6611', label: 'Intérêts des emprunts et dettes PCG', type: 'charge', system: 'pcg_france' },
    { code: '6614', label: "Intérêts emprunts établissements de crédit PCG", type: 'charge', system: 'pcg_france' },
    { code: '6616', label: 'Intérêts bancaires et opérations de financement PCG', type: 'charge', system: 'pcg_france' },
    { code: '665', label: 'Escomptes accordés PCG', type: 'charge', system: 'pcg_france' },
    { code: '666', label: 'Pertes de change PCG', type: 'charge', system: 'pcg_france' },
    { code: '667', label: 'Charges nettes sur cessions de VMP', type: 'charge', system: 'pcg_france' },
    { code: '671', label: 'Charges exceptionnelles sur opérations de gestion PCG', type: 'charge', system: 'pcg_france' },
    { code: '6711', label: 'Pénalités sur marchés et dédits PCG', type: 'charge', system: 'pcg_france' },
    { code: '6712', label: 'Pénalités amendes fiscales et pénales PCG', type: 'charge', system: 'pcg_france' },
    { code: '675', label: "Valeurs comptables des éléments d'actif cédés PCG", type: 'charge', system: 'pcg_france' },
    { code: '6751', label: 'VNC immobilisations incorporelles cédées PCG', type: 'charge', system: 'pcg_france' },
    { code: '6752', label: 'VNC immobilisations corporelles cédées PCG', type: 'charge', system: 'pcg_france' },
    { code: '678', label: 'Autres charges exceptionnelles PCG', type: 'charge', system: 'pcg_france' },
    { code: '681', label: "Dotations amortissements dépréciations provisions exploitation PCG", type: 'charge', system: 'pcg_france' },
    { code: '6811', label: 'Dotations amort. immobilisations incorp. et corp. PCG', type: 'charge', system: 'pcg_france' },
    { code: '68111', label: 'Dotations amort. immobilisations incorporelles PCG', type: 'charge', system: 'pcg_france' },
    { code: '68112', label: 'Dotations amort. immobilisations corporelles PCG', type: 'charge', system: 'pcg_france' },
    { code: '6815', label: 'Dotations aux provisions PCG', type: 'charge', system: 'pcg_france' },
    { code: '68151', label: 'Dotations provisions pour risques PCG', type: 'charge', system: 'pcg_france' },
    { code: '6816', label: 'Dotations dépréciations immobilisations PCG', type: 'charge', system: 'pcg_france' },
    { code: '6817', label: 'Dotations dépréciations actifs circulants PCG', type: 'charge', system: 'pcg_france' },
    { code: '686', label: 'Dotations charges financières PCG', type: 'charge', system: 'pcg_france' },
    { code: '687', label: 'Dotations charges exceptionnelles PCG', type: 'charge', system: 'pcg_france' },
    { code: '691', label: 'Participation des salariés aux résultats PCG', type: 'charge', system: 'pcg_france' },
    { code: '695', label: 'Impôts sur les bénéfices PCG', type: 'charge', system: 'pcg_france' },
    { code: '6951', label: 'Impôts dus en France PCG', type: 'charge', system: 'pcg_france' },
    { code: '6952', label: "Impôts dus à l'étranger PCG", type: 'charge', system: 'pcg_france' },
    // ══ PCG CLASSE 7 ══
    { code: '701', label: 'Ventes de produits finis PCG', type: 'produit', system: 'pcg_france' },
    { code: '702', label: 'Ventes de produits intermédiaires PCG', type: 'produit', system: 'pcg_france' },
    { code: '703', label: 'Ventes de produits résiduels PCG', type: 'produit', system: 'pcg_france' },
    { code: '704', label: 'Travaux PCG', type: 'produit', system: 'pcg_france' },
    { code: '705', label: 'Études PCG', type: 'produit', system: 'pcg_france' },
    { code: '706', label: 'Prestations de services PCG', type: 'produit', system: 'pcg_france' },
    { code: '707', label: 'Ventes de marchandises PCG', type: 'produit', system: 'pcg_france' },
    { code: '708', label: 'Produits des activités annexes PCG', type: 'produit', system: 'pcg_france' },
    { code: '7082', label: 'Commissions et courtages PCG', type: 'produit', system: 'pcg_france' },
    { code: '7083', label: 'Locations diverses PCG', type: 'produit', system: 'pcg_france' },
    { code: '7085', label: 'Ports et frais accessoires facturés PCG', type: 'produit', system: 'pcg_france' },
    { code: '7088', label: "Autres produits d'activités annexes PCG", type: 'produit', system: 'pcg_france' },
    { code: '7131', label: 'Variation en-cours production de biens PCG', type: 'produit', system: 'pcg_france' },
    { code: '7132', label: 'Variation en-cours production de services PCG', type: 'produit', system: 'pcg_france' },
    { code: '7133', label: 'Variation stocks produits finis PCG', type: 'produit', system: 'pcg_france' },
    { code: '721', label: 'Immobilisations incorporelles PCG', type: 'produit', system: 'pcg_france' },
    { code: '722', label: 'Immobilisations corporelles PCG', type: 'produit', system: 'pcg_france' },
    { code: '741', label: "Subventions de l'État PCG", type: 'produit', system: 'pcg_france' },
    { code: '7411', label: "Subventions de l'État entreprise PCG", type: 'produit', system: 'pcg_france' },
    { code: '7413', label: 'Subventions régionales PCG', type: 'produit', system: 'pcg_france' },
    { code: '7414', label: 'Subventions départementales PCG', type: 'produit', system: 'pcg_france' },
    { code: '7415', label: 'Subventions communales PCG', type: 'produit', system: 'pcg_france' },
    { code: '7417', label: 'Subventions des organismes internationaux PCG', type: 'produit', system: 'pcg_france' },
    { code: '7418', label: "Autres subventions d'exploitation PCG", type: 'produit', system: 'pcg_france' },
    { code: '751', label: 'Redevances pour concessions brevets licences PCG prod', type: 'produit', system: 'pcg_france' },
    { code: '7511', label: 'Redevances pour concessions PCG', type: 'produit', system: 'pcg_france' },
    { code: '7516', label: 'Redevances pour brevets et licences PCG', type: 'produit', system: 'pcg_france' },
    { code: '7517', label: 'Redevances pour logiciels PCG', type: 'produit', system: 'pcg_france' },
    { code: '758', label: 'Produits divers de gestion courante PCG', type: 'produit', system: 'pcg_france' },
    { code: '761', label: 'Produits de participations PCG', type: 'produit', system: 'pcg_france' },
    { code: '7611', label: 'Revenus des titres de participation PCG', type: 'produit', system: 'pcg_france' },
    { code: '762', label: 'Produits des autres immobilisations financières PCG', type: 'produit', system: 'pcg_france' },
    { code: '7622', label: 'Revenus des prêts PCG', type: 'produit', system: 'pcg_france' },
    { code: '764', label: 'Revenus des VMP PCG', type: 'produit', system: 'pcg_france' },
    { code: '765', label: 'Escomptes obtenus PCG', type: 'produit', system: 'pcg_france' },
    { code: '766', label: 'Gains de change PCG', type: 'produit', system: 'pcg_france' },
    { code: '767', label: 'Produits nets sur cessions de VMP PCG', type: 'produit', system: 'pcg_france' },
    { code: '768', label: 'Autres produits financiers PCG', type: 'produit', system: 'pcg_france' },
    { code: '771', label: 'Produits exceptionnels sur opérations de gestion PCG', type: 'produit', system: 'pcg_france' },
    { code: '7711', label: 'Pénalités et dédits reçus PCG', type: 'produit', system: 'pcg_france' },
    { code: '7714', label: 'Rentrées sur créances irrécouvrables PCG', type: 'produit', system: 'pcg_france' },
    { code: '775', label: "Produits des cessions d'éléments d'actif PCG", type: 'produit', system: 'pcg_france' },
    { code: '7751', label: 'Produits cessions immo. incorporelles PCG', type: 'produit', system: 'pcg_france' },
    { code: '7752', label: 'Produits cessions immo. corporelles PCG', type: 'produit', system: 'pcg_france' },
    { code: '777', label: "Quote-part subventions d'investissement virée au résultat PCG", type: 'produit', system: 'pcg_france' },
    { code: '778', label: 'Autres produits exceptionnels PCG', type: 'produit', system: 'pcg_france' },
    { code: '781', label: "Reprises exploitation PCG", type: 'produit', system: 'pcg_france' },
    { code: '7811', label: 'Reprises amortissements immobilisations PCG', type: 'produit', system: 'pcg_france' },
    { code: '7815', label: 'Reprises sur provisions PCG', type: 'produit', system: 'pcg_france' },
    { code: '7816', label: 'Reprises dépréciations immobilisations PCG', type: 'produit', system: 'pcg_france' },
    { code: '7817', label: 'Reprises dépréciations actifs circulants PCG', type: 'produit', system: 'pcg_france' },
    { code: '786', label: 'Reprises financières PCG', type: 'produit', system: 'pcg_france' },
    { code: '787', label: 'Reprises exceptionnelles PCG', type: 'produit', system: 'pcg_france' },
    { code: '791', label: "Transferts de charges d'exploitation PCG", type: 'produit', system: 'pcg_france' },
    { code: '796', label: 'Transferts de charges financières PCG', type: 'produit', system: 'pcg_france' },
    { code: '797', label: 'Transferts de charges exceptionnelles PCG', type: 'produit', system: 'pcg_france' },
  ];

  // Supprimer les anciens comptes système (sans entreprise)
  // suppression d sactiv e
  // console.log('Anciens comptes supprimés : ' + deleted.count);

  // Insérer tous les nouveaux comptes
  const result = await prisma.account.createMany({
    data: comptes.map((c) => ({
      code: c.code,
      label: c.label,
      classe: c.classe,
      type: c.type,
      system: c.system,
      company_id: null,
    })),
    skipDuplicates: true,
  });

  const totalOHADA = await prisma.account.count({ where: { system: 'ohada', company_id: null } });
  const totalPCG = await prisma.account.count({ where: { system: 'pcg_france', company_id: null } });

  console.log('Comptes insérés : ' + result.count);
  console.log('OHADA : ' + totalOHADA + ' comptes');
  console.log('PCG France : ' + totalPCG + ' comptes');
  console.log('TOTAL : ' + (totalOHADA + totalPCG) + ' comptes');
  console.log('TERMINE !');
}

main()
  .catch((e) => { console.error('Erreur :', e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });


