// @ts-nocheck
import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

// is_detail: true  = compte mouvementable (utilisé dans les écritures)
// is_detail: false = compte regroupement (titre de classe/groupe)

const ohada = [

  // ══════════════════════════════════════════════════════
  //  CLASSE 1 — COMPTES DE RESSOURCES DURABLES
  // ══════════════════════════════════════════════════════
  { code: '10',   label: 'Capital et réserves',                              type: 'passif', is_detail: false },
  { code: '101',  label: 'Capital social',                                   type: 'passif', is_detail: false },
  { code: '1011', label: 'Capital souscrit non appelé',                      type: 'passif', is_detail: true  },
  { code: '1012', label: 'Capital souscrit appelé non versé',                type: 'passif', is_detail: true  },
  { code: '1013', label: 'Capital souscrit appelé versé non amorti',         type: 'passif', is_detail: true  },
  { code: '1014', label: 'Capital souscrit versé et amorti',                 type: 'passif', is_detail: true  },
  { code: '102',  label: 'Capital par dotation',                             type: 'passif', is_detail: true  },
  { code: '103',  label: 'Capital personnel',                                type: 'passif', is_detail: true  },
  { code: '104',  label: "Compte de l'exploitant",                           type: 'passif', is_detail: true  },
  { code: '105',  label: 'Primes liées aux capitaux propres',                type: 'passif', is_detail: false },
  { code: '1051', label: "Primes d'émission",                                type: 'passif', is_detail: true  },
  { code: '1052', label: "Primes d'apport",                                  type: 'passif', is_detail: true  },
  { code: '1053', label: 'Primes de fusion',                                 type: 'passif', is_detail: true  },
  { code: '1055', label: 'Primes de conversion',                             type: 'passif', is_detail: true  },
  { code: '106',  label: 'Écarts de réévaluation',                          type: 'passif', is_detail: true  },
  { code: '11',   label: 'Réserves',                                         type: 'passif', is_detail: false },
  { code: '111',  label: 'Réserve légale',                                   type: 'passif', is_detail: true  },
  { code: '112',  label: 'Réserves statutaires ou contractuelles',           type: 'passif', is_detail: true  },
  { code: '113',  label: 'Réserves réglementées',                            type: 'passif', is_detail: true  },
  { code: '118',  label: 'Autres réserves',                                  type: 'passif', is_detail: true  },
  { code: '12',   label: 'Report à nouveau',                                 type: 'passif', is_detail: false },
  { code: '121',  label: 'Report à nouveau créditeur',                       type: 'passif', is_detail: true  },
  { code: '129',  label: 'Report à nouveau débiteur',                        type: 'passif', is_detail: true  },
  { code: '13',   label: "Résultat de l'exercice",                           type: 'passif', is_detail: false },
  { code: '130',  label: "Résultat en instance d'affectation",               type: 'passif', is_detail: true  },
  { code: '131',  label: 'Résultat net bénéfice',                            type: 'passif', is_detail: true  },
  { code: '139',  label: 'Résultat net perte',                               type: 'passif', is_detail: true  },
  { code: '14',   label: "Subventions d'investissement",                     type: 'passif', is_detail: false },
  { code: '141',  label: "Subventions d'équipement État",                    type: 'passif', is_detail: true  },
  { code: '142',  label: "Subventions d'équipement collectivités locales",   type: 'passif', is_detail: true  },
  { code: '143',  label: "Subventions d'équipement entreprises publiques",   type: 'passif', is_detail: true  },
  { code: '148',  label: "Autres subventions d'investissement",              type: 'passif', is_detail: true  },
  { code: '15',   label: 'Provisions réglementées et fonds assimilés',       type: 'passif', is_detail: false },
  { code: '151',  label: 'Amortissements dérogatoires',                      type: 'passif', is_detail: true  },
  { code: '152',  label: 'Plus-values à réinvestir',                         type: 'passif', is_detail: true  },
  { code: '153',  label: 'Provisions pour hausse des prix',                  type: 'passif', is_detail: true  },
  { code: '154',  label: 'Provision spéciale de réévaluation',               type: 'passif', is_detail: true  },
  { code: '155',  label: 'Provisions réglementées diverses',                 type: 'passif', is_detail: true  },
  { code: '16',   label: 'Emprunts et dettes financières diverses',          type: 'passif', is_detail: false },
  { code: '161',  label: 'Emprunts obligataires',                            type: 'passif', is_detail: false },
  { code: '1611', label: 'Emprunts obligataires ordinaires',                 type: 'passif', is_detail: true  },
  { code: '1612', label: 'Emprunts obligataires convertibles',               type: 'passif', is_detail: true  },
  { code: '162',  label: 'Emprunts auprès des établissements de crédit',     type: 'passif', is_detail: true  },
  { code: '163',  label: "Avances reçues de l'État",                        type: 'passif', is_detail: true  },
  { code: '164',  label: 'Avances reçues et comptes courants bloqués',      type: 'passif', is_detail: true  },
  { code: '165',  label: 'Dépôts et cautionnements reçus',                  type: 'passif', is_detail: true  },
  { code: '166',  label: 'Intérêts courus sur emprunts',                    type: 'passif', is_detail: true  },
  { code: '167',  label: 'Dettes sur contrats de location-financement',     type: 'passif', is_detail: true  },
  { code: '168',  label: 'Autres emprunts et dettes financières',           type: 'passif', is_detail: true  },
  { code: '17',   label: 'Dettes de location-financement',                  type: 'passif', is_detail: false },
  { code: '171',  label: 'Emprunts équivalents — crédit-bail immobilier',   type: 'passif', is_detail: true  },
  { code: '172',  label: 'Emprunts équivalents — crédit-bail mobilier',     type: 'passif', is_detail: true  },
  { code: '173',  label: 'Emprunts équivalents — autres contrats',          type: 'passif', is_detail: true  },
  { code: '18',   label: 'Dettes liées à des participations',               type: 'passif', is_detail: false },
  { code: '181',  label: 'Dettes liées à des participations groupe',        type: 'passif', is_detail: true  },
  { code: '185',  label: 'Comptes de liaison groupe',                       type: 'passif', is_detail: true  },
  { code: '186',  label: 'Comptes de liaison succursales / agences',        type: 'passif', is_detail: true  },
  { code: '19',   label: 'Provisions financières pour risques et charges',  type: 'passif', is_detail: false },
  { code: '191',  label: 'Provisions pour risques financiers',              type: 'passif', is_detail: true  },
  { code: '194',  label: 'Provisions pour pertes de change',                type: 'passif', is_detail: true  },
  { code: '195',  label: 'Provisions pour charges à répartir',             type: 'passif', is_detail: true  },
  { code: '199',  label: 'Autres provisions pour risques et charges',      type: 'passif', is_detail: true  },

  // ══════════════════════════════════════════════════════
  //  CLASSE 2 — COMPTES D'ACTIF IMMOBILISÉ
  // ══════════════════════════════════════════════════════
  { code: '20',   label: 'Charges immobilisées',                            type: 'actif',  is_detail: false },
  { code: '201',  label: 'Frais de développement',                          type: 'actif',  is_detail: true  },
  { code: '202',  label: 'Brevets, licences, concessions et droits',        type: 'actif',  is_detail: true  },
  { code: '203',  label: 'Logiciels informatiques',                         type: 'actif',  is_detail: true  },
  { code: '204',  label: 'Marques',                                         type: 'actif',  is_detail: true  },
  { code: '205',  label: 'Fonds commercial',                                type: 'actif',  is_detail: true  },
  { code: '206',  label: 'Droit au bail',                                   type: 'actif',  is_detail: true  },
  { code: '207',  label: "Frais d'acquisition des immobilisations",         type: 'actif',  is_detail: true  },
  { code: '208',  label: 'Autres immobilisations incorporelles',            type: 'actif',  is_detail: true  },
  { code: '21',   label: 'Terrains',                                        type: 'actif',  is_detail: false },
  { code: '211',  label: 'Terrains nus',                                    type: 'actif',  is_detail: true  },
  { code: '212',  label: 'Terrains aménagés',                               type: 'actif',  is_detail: true  },
  { code: '213',  label: 'Sites naturels',                                  type: 'actif',  is_detail: true  },
  { code: '214',  label: 'Terrains de gisement',                           type: 'actif',  is_detail: true  },
  { code: '215',  label: 'Terrains bâtis',                                 type: 'actif',  is_detail: true  },
  { code: '22',   label: 'Bâtiments',                                      type: 'actif',  is_detail: false },
  { code: '221',  label: 'Bâtiments sur sol propre',                       type: 'actif',  is_detail: true  },
  { code: '222',  label: 'Bâtiments sur sol autrui',                       type: 'actif',  is_detail: true  },
  { code: '223',  label: 'Ouvrages sur sol propre',                        type: 'actif',  is_detail: true  },
  { code: '224',  label: 'Ouvrages sur sol autrui',                        type: 'actif',  is_detail: true  },
  { code: '225',  label: 'Aménagements et agencements des bâtiments',      type: 'actif',  is_detail: true  },
  { code: '23',   label: 'Aménagements, agencements et installations',     type: 'actif',  is_detail: false },
  { code: '231',  label: 'Aménagements de terrains',                       type: 'actif',  is_detail: true  },
  { code: '232',  label: 'Agencements et aménagements des bâtiments',      type: 'actif',  is_detail: true  },
  { code: '234',  label: 'Installations et aménagements divers',           type: 'actif',  is_detail: true  },
  { code: '24',   label: 'Matériel',                                       type: 'actif',  is_detail: false },
  { code: '241',  label: 'Matériel et outillage industriel et commercial',  type: 'actif',  is_detail: true  },
  { code: '242',  label: 'Matériel et outillage agricole',                 type: 'actif',  is_detail: true  },
  { code: '244',  label: "Matériel d'emballage récupérable",               type: 'actif',  is_detail: true  },
  { code: '245',  label: 'Matériel informatique',                          type: 'actif',  is_detail: true  },
  { code: '246',  label: 'Mobilier, matériel et équipement de bureau',     type: 'actif',  is_detail: true  },
  { code: '247',  label: "Matériel d'éclairage et de sécurité",            type: 'actif',  is_detail: true  },
  { code: '248',  label: 'Autres matériels',                               type: 'actif',  is_detail: true  },
  { code: '25',   label: 'Matériel de transport',                          type: 'actif',  is_detail: false },
  { code: '251',  label: 'Véhicules',                                      type: 'actif',  is_detail: true  },
  { code: '252',  label: 'Matériel de transport fluvial et maritime',      type: 'actif',  is_detail: true  },
  { code: '253',  label: 'Matériel de transport ferroviaire',              type: 'actif',  is_detail: true  },
  { code: '254',  label: 'Matériel de transport aérien',                   type: 'actif',  is_detail: true  },
  { code: '26',   label: 'Immobilisations financières',                    type: 'actif',  is_detail: false },
  { code: '261',  label: 'Titres de participation',                        type: 'actif',  is_detail: true  },
  { code: '262',  label: 'Autres titres immobilisés',                      type: 'actif',  is_detail: true  },
  { code: '265',  label: 'Dépôts et cautionnements versés',                type: 'actif',  is_detail: true  },
  { code: '266',  label: 'Prêts et créances non courantes',                type: 'actif',  is_detail: true  },
  { code: '267',  label: 'Créances rattachées à des participations',       type: 'actif',  is_detail: true  },
  { code: '27',   label: 'Autres immobilisations financières',             type: 'actif',  is_detail: false },
  { code: '271',  label: 'Prêts accordés',                                 type: 'actif',  is_detail: true  },
  { code: '275',  label: 'Intérêts courus sur prêts',                     type: 'actif',  is_detail: true  },
  { code: '276',  label: 'Autres créances immobilisées',                  type: 'actif',  is_detail: true  },
  { code: '28',   label: "Amortissements des immobilisations",             type: 'actif',  is_detail: false },
  { code: '281',  label: 'Amort. immobilisations incorporelles',           type: 'actif',  is_detail: true  },
  { code: '2811', label: 'Amort. frais de développement',                 type: 'actif',  is_detail: true  },
  { code: '2812', label: 'Amort. brevets et licences',                    type: 'actif',  is_detail: true  },
  { code: '2813', label: 'Amort. logiciels',                              type: 'actif',  is_detail: true  },
  { code: '282',  label: 'Amort. terrains',                               type: 'actif',  is_detail: true  },
  { code: '283',  label: 'Amort. bâtiments',                              type: 'actif',  is_detail: true  },
  { code: '2831', label: 'Amort. bâtiments sur sol propre',              type: 'actif',  is_detail: true  },
  { code: '2832', label: 'Amort. bâtiments sur sol autrui',              type: 'actif',  is_detail: true  },
  { code: '284',  label: 'Amort. matériel',                               type: 'actif',  is_detail: true  },
  { code: '2841', label: 'Amort. matériel et outillage',                 type: 'actif',  is_detail: true  },
  { code: '2845', label: 'Amort. matériel informatique',                 type: 'actif',  is_detail: true  },
  { code: '2846', label: 'Amort. mobilier et équipement bureau',         type: 'actif',  is_detail: true  },
  { code: '285',  label: 'Amort. matériel de transport',                 type: 'actif',  is_detail: true  },
  { code: '29',   label: "Dépréciations des immobilisations",             type: 'actif',  is_detail: false },
  { code: '291',  label: 'Dépréc. immobilisations incorporelles',         type: 'actif',  is_detail: true  },
  { code: '295',  label: 'Dépréc. immobilisations financières',           type: 'actif',  is_detail: true  },

  // ══════════════════════════════════════════════════════
  //  CLASSE 3 — COMPTES DE STOCKS
  // ══════════════════════════════════════════════════════
  { code: '30',   label: 'Stocks',                                         type: 'actif',  is_detail: false },
  { code: '31',   label: 'Marchandises',                                   type: 'actif',  is_detail: false },
  { code: '311',  label: 'Marchandises A',                                 type: 'actif',  is_detail: true  },
  { code: '312',  label: 'Marchandises B',                                 type: 'actif',  is_detail: true  },
  { code: '318',  label: 'Autres marchandises',                            type: 'actif',  is_detail: true  },
  { code: '319',  label: 'Dépréciations des marchandises',                 type: 'actif',  is_detail: true  },
  { code: '32',   label: 'Matières premières et fournitures liées',        type: 'actif',  is_detail: false },
  { code: '321',  label: 'Matières premières A',                           type: 'actif',  is_detail: true  },
  { code: '322',  label: 'Matières premières B',                           type: 'actif',  is_detail: true  },
  { code: '328',  label: 'Autres matières premières',                      type: 'actif',  is_detail: true  },
  { code: '33',   label: 'Autres approvisionnements',                      type: 'actif',  is_detail: false },
  { code: '331',  label: 'Matières consommables',                          type: 'actif',  is_detail: true  },
  { code: '332',  label: 'Fournitures de bureau',                          type: 'actif',  is_detail: true  },
  { code: '333',  label: "Fournitures d'atelier et d'usine",               type: 'actif',  is_detail: true  },
  { code: '334',  label: 'Fournitures de magasin',                         type: 'actif',  is_detail: true  },
  { code: '335',  label: 'Fournitures informatiques',                      type: 'actif',  is_detail: true  },
  { code: '338',  label: 'Autres fournitures',                             type: 'actif',  is_detail: true  },
  { code: '34',   label: 'Produits en cours',                              type: 'actif',  is_detail: false },
  { code: '341',  label: 'Produits en cours A',                            type: 'actif',  is_detail: true  },
  { code: '342',  label: 'Produits en cours B',                            type: 'actif',  is_detail: true  },
  { code: '35',   label: 'Services en cours',                              type: 'actif',  is_detail: false },
  { code: '351',  label: 'Services en cours A',                            type: 'actif',  is_detail: true  },
  { code: '352',  label: 'Services en cours B',                            type: 'actif',  is_detail: true  },
  { code: '36',   label: 'Produits finis',                                 type: 'actif',  is_detail: false },
  { code: '361',  label: 'Produits finis A',                               type: 'actif',  is_detail: true  },
  { code: '362',  label: 'Produits finis B',                               type: 'actif',  is_detail: true  },
  { code: '37',   label: 'Produits intermédiaires et résiduels',           type: 'actif',  is_detail: false },
  { code: '371',  label: 'Produits intermédiaires',                        type: 'actif',  is_detail: true  },
  { code: '372',  label: 'Produits résiduels et matières de récupération', type: 'actif',  is_detail: true  },
  { code: '38',   label: 'Stocks en cours de route et en dépôt',           type: 'actif',  is_detail: false },
  { code: '381',  label: 'Stocks en cours de route',                       type: 'actif',  is_detail: true  },
  { code: '382',  label: 'Stocks en dépôt',                                type: 'actif',  is_detail: true  },
  { code: '39',   label: 'Dépréciations des stocks',                       type: 'actif',  is_detail: false },
  { code: '391',  label: 'Dépréc. marchandises',                           type: 'actif',  is_detail: true  },
  { code: '392',  label: 'Dépréc. matières premières',                     type: 'actif',  is_detail: true  },
  { code: '396',  label: 'Dépréc. produits finis',                         type: 'actif',  is_detail: true  },

  // ══════════════════════════════════════════════════════
  //  CLASSE 4 — COMPTES DE TIERS
  // ══════════════════════════════════════════════════════
  { code: '40',   label: 'Fournisseurs et comptes rattachés',              type: 'passif', is_detail: false },
  { code: '401',  label: 'Fournisseurs',                                    type: 'passif', is_detail: true  },
  { code: '402',  label: 'Fournisseurs — effets à payer',                   type: 'passif', is_detail: true  },
  { code: '403',  label: 'Fournisseurs — avances reçues',                   type: 'passif', is_detail: true  },
  { code: '404',  label: 'Fournisseurs — retenues de garantie',             type: 'passif', is_detail: true  },
  { code: '405',  label: 'Fournisseurs, factures non encore parvenues',     type: 'passif', is_detail: true  },
  { code: '408',  label: 'Fournisseurs de services',                        type: 'passif', is_detail: true  },
  { code: '409',  label: 'Fournisseurs — avances et acomptes versés',       type: 'actif',  is_detail: true  },
  { code: '41',   label: 'Clients et comptes rattachés',                    type: 'actif',  is_detail: false },
  { code: '411',  label: 'Clients',                                         type: 'actif',  is_detail: true  },
  { code: '412',  label: "Clients — effets à recevoir",                     type: 'actif',  is_detail: true  },
  { code: '413',  label: 'Clients — avances reçues',                        type: 'passif', is_detail: true  },
  { code: '414',  label: 'Clients — retenues de garantie',                  type: 'actif',  is_detail: true  },
  { code: '415',  label: "Clients — effets remis à l'escompte",             type: 'actif',  is_detail: true  },
  { code: '416',  label: "Créances sur cessions courantes d'immob.",        type: 'actif',  is_detail: true  },
  { code: '418',  label: 'Clients — produits à recevoir',                   type: 'actif',  is_detail: true  },
  { code: '419',  label: 'Clients créditeurs — avances et acomptes',        type: 'passif', is_detail: true  },
  { code: '42',   label: 'Personnel',                                       type: 'passif', is_detail: false },
  { code: '421',  label: 'Personnel — rémunérations dues',                  type: 'passif', is_detail: true  },
  { code: '422',  label: 'Personnel — acomptes et avances',                 type: 'actif',  is_detail: true  },
  { code: '423',  label: 'Personnel — oppositions saisies-arrêts',          type: 'passif', is_detail: true  },
  { code: '424',  label: 'Personnel — œuvres sociales',                     type: 'passif', is_detail: true  },
  { code: '425',  label: 'Personnel — charges à payer',                     type: 'passif', is_detail: true  },
  { code: '426',  label: 'Personnel — dépôts',                             type: 'passif', is_detail: true  },
  { code: '428',  label: 'Personnel — autres',                             type: 'passif', is_detail: true  },
  { code: '43',   label: 'Sécurité sociale et organismes sociaux',         type: 'passif', is_detail: false },
  { code: '431',  label: 'CNSS (Gabon)',                                    type: 'passif', is_detail: true  },
  { code: '432',  label: 'Caisses de retraite',                            type: 'passif', is_detail: true  },
  { code: '433',  label: 'Mutuelles',                                      type: 'passif', is_detail: true  },
  { code: '434',  label: 'CNAMGS (Gabon)',                                  type: 'passif', is_detail: true  },
  { code: '438',  label: 'Organismes sociaux — autres',                    type: 'passif', is_detail: true  },
  { code: '44',   label: 'État et collectivités publiques',                type: 'passif', is_detail: false },
  { code: '441',  label: 'État — impôts et taxes',                         type: 'passif', is_detail: true  },
  { code: '4411', label: 'Impôt sur les sociétés à payer',                 type: 'passif', is_detail: true  },
  { code: '4413', label: 'Impôt minimum forfaitaire (IMF)',                 type: 'passif', is_detail: true  },
  { code: '4414', label: 'TVA collectée',                                  type: 'passif', is_detail: true  },
  { code: '4415', label: 'TVA déductible sur achats',                      type: 'actif',  is_detail: true  },
  { code: '4416', label: 'TVA sur encaissements',                          type: 'passif', is_detail: true  },
  { code: '4417', label: 'TVA sur décaissements',                          type: 'actif',  is_detail: true  },
  { code: '4418', label: 'TVA — crédits de TVA à reporter',                type: 'actif',  is_detail: true  },
  { code: '442',  label: 'État — impôts sur les bénéfices',                type: 'passif', is_detail: true  },
  { code: '443',  label: 'État — autres impôts et taxes',                  type: 'passif', is_detail: true  },
  { code: '444',  label: "État — taxes sur le chiffre d'affaires",         type: 'passif', is_detail: true  },
  { code: '445',  label: 'État — acomptes sur impôts',                     type: 'actif',  is_detail: true  },
  { code: '4451', label: 'Acomptes IS',                                    type: 'actif',  is_detail: true  },
  { code: '446',  label: 'État — subventions à recevoir',                  type: 'actif',  is_detail: true  },
  { code: '447',  label: 'État — impôts retenus à la source',              type: 'passif', is_detail: true  },
  { code: '448',  label: 'État — charges à payer et produits à recevoir',  type: 'passif', is_detail: true  },
  { code: '449',  label: 'État — créditeurs divers',                       type: 'passif', is_detail: true  },
  { code: '45',   label: 'Organismes internationaux',                      type: 'passif', is_detail: false },
  { code: '451',  label: 'Banque mondiale',                                type: 'passif', is_detail: true  },
  { code: '452',  label: 'Union européenne',                               type: 'passif', is_detail: true  },
  { code: '455',  label: 'Autres organismes internationaux',               type: 'passif', is_detail: true  },
  { code: '46',   label: 'Associés et groupe',                             type: 'passif', is_detail: false },
  { code: '461',  label: "Associés — apports en société",                  type: 'passif', is_detail: true  },
  { code: '462',  label: 'Associés — capital à rembourser',                type: 'passif', is_detail: true  },
  { code: '463',  label: 'Associés — dividendes à payer',                  type: 'passif', is_detail: true  },
  { code: '464',  label: 'Associés — comptes courants',                    type: 'passif', is_detail: true  },
  { code: '465',  label: 'Associés — créances sur comptes courants',       type: 'actif',  is_detail: true  },
  { code: '47',   label: 'Débiteurs et créditeurs divers',                 type: 'actif',  is_detail: false },
  { code: '471',  label: 'Débiteurs divers',                               type: 'actif',  is_detail: true  },
  { code: '472',  label: 'Créditeurs divers',                              type: 'passif', is_detail: true  },
  { code: '473',  label: 'Débiteurs et créditeurs — retenues de garantie', type: 'actif',  is_detail: true  },
  { code: '474',  label: 'Compte de répartition périodique des charges',   type: 'actif',  is_detail: true  },
  { code: '476',  label: 'Différences de conversion — actif',              type: 'actif',  is_detail: true  },
  { code: '477',  label: 'Différences de conversion — passif',             type: 'passif', is_detail: true  },
  { code: '478',  label: 'Autres débiteurs divers',                        type: 'actif',  is_detail: true  },
  { code: '48',   label: 'Créances et dettes hors activité ordinaire',     type: 'actif',  is_detail: false },
  { code: '481',  label: 'Créances sur cessions immobilisations (HAO)',    type: 'actif',  is_detail: true  },
  { code: '482',  label: 'Créances sur cessions de titres de placement',   type: 'actif',  is_detail: true  },
  { code: '485',  label: 'Dettes sur acquisitions immobilisations (HAO)',  type: 'passif', is_detail: true  },
  { code: '486',  label: "Charges constatées d'avance",                    type: 'actif',  is_detail: true  },
  { code: '487',  label: "Produits constatés d'avance",                    type: 'passif', is_detail: true  },
  { code: '491',  label: 'Dépréciations comptes clients',                  type: 'actif',  is_detail: true  },
  { code: '499',  label: 'Dépréciations autres comptes de tiers',          type: 'actif',  is_detail: true  },

  // ══════════════════════════════════════════════════════
  //  CLASSE 5 — COMPTES DE TRÉSORERIE
  // ══════════════════════════════════════════════════════
  { code: '50',   label: 'Titres de placement',                            type: 'tresorerie', is_detail: false },
  { code: '501',  label: 'Titres de placement — actions',                  type: 'tresorerie', is_detail: true  },
  { code: '502',  label: 'Titres de placement — obligations',              type: 'tresorerie', is_detail: true  },
  { code: '503',  label: 'Titres de placement — bons du trésor',           type: 'tresorerie', is_detail: true  },
  { code: '508',  label: 'Autres titres de placement',                     type: 'tresorerie', is_detail: true  },
  { code: '509',  label: 'Dépréciations des titres de placement',          type: 'tresorerie', is_detail: true  },
  { code: '51',   label: 'Valeurs à encaisser',                            type: 'tresorerie', is_detail: false },
  { code: '511',  label: 'Valeurs à encaisser en portefeuille',            type: 'tresorerie', is_detail: true  },
  { code: '514',  label: 'Virements de fonds en cours',                    type: 'tresorerie', is_detail: true  },
  { code: '515',  label: 'Chèques à encaisser',                            type: 'tresorerie', is_detail: true  },
  { code: '52',   label: 'Banques',                                        type: 'tresorerie', is_detail: false },
  { code: '521',  label: 'Banque 1 — compte courant',                      type: 'tresorerie', is_detail: true  },
  { code: '522',  label: 'Banque 2 — compte courant',                      type: 'tresorerie', is_detail: true  },
  { code: '523',  label: 'Banque 3 — compte courant',                      type: 'tresorerie', is_detail: true  },
  { code: '524',  label: 'Banque — compte épargne',                        type: 'tresorerie', is_detail: true  },
  { code: '525',  label: 'Banque — compte à terme',                        type: 'tresorerie', is_detail: true  },
  { code: '526',  label: 'Comptes courants postaux (CCP)',                  type: 'tresorerie', is_detail: true  },
  { code: '528',  label: 'Autres banques',                                 type: 'tresorerie', is_detail: true  },
  { code: '53',   label: 'Établissements financiers et assimilés',         type: 'tresorerie', is_detail: false },
  { code: '531',  label: "Caisse d'épargne",                               type: 'tresorerie', is_detail: true  },
  { code: '532',  label: 'Trésor public',                                  type: 'tresorerie', is_detail: true  },
  { code: '57',   label: 'Caisse',                                         type: 'tresorerie', is_detail: false },
  { code: '571',  label: 'Caisse siège social',                            type: 'tresorerie', is_detail: true  },
  { code: '572',  label: 'Caisse succursale / agence',                     type: 'tresorerie', is_detail: true  },
  { code: '573',  label: 'Caisse en devises',                              type: 'tresorerie', is_detail: true  },
  { code: '578',  label: 'Caisse — autres',                                type: 'tresorerie', is_detail: true  },
  { code: '58',   label: "Régies d'avances et accréditifs",                type: 'tresorerie', is_detail: false },
  { code: '581',  label: "Régies d'avances",                               type: 'tresorerie', is_detail: true  },
  { code: '582',  label: 'Accréditifs',                                    type: 'tresorerie', is_detail: true  },
  { code: '59',   label: 'Dépréciations et virements de fonds',            type: 'tresorerie', is_detail: false },
  { code: '591',  label: 'Dépréciations des comptes de trésorerie',        type: 'tresorerie', is_detail: true  },
  { code: '596',  label: 'Virements internes de fonds',                    type: 'tresorerie', is_detail: true  },

  // ══════════════════════════════════════════════════════
  //  CLASSE 6 — CHARGES DES ACTIVITÉS ORDINAIRES
  // ══════════════════════════════════════════════════════
  { code: '60',   label: 'Achats et variations de stocks',                 type: 'charge',  is_detail: false },
  { code: '601',  label: 'Achats de marchandises',                         type: 'charge',  is_detail: true  },
  { code: '602',  label: 'Achats de matières premières',                   type: 'charge',  is_detail: true  },
  { code: '603',  label: 'Achats de matières consommables',                type: 'charge',  is_detail: true  },
  { code: '604',  label: 'Achats de produits finis',                       type: 'charge',  is_detail: true  },
  { code: '605',  label: 'Achats de matériaux',                            type: 'charge',  is_detail: true  },
  { code: '606',  label: 'Achats de fournitures',                          type: 'charge',  is_detail: false },
  { code: '6061', label: 'Achats fournitures non stockables (eau, énergie)', type: 'charge', is_detail: true },
  { code: '6062', label: 'Achats de fournitures de bureau',                type: 'charge',  is_detail: true  },
  { code: '6063', label: 'Achats de petit équipement',                     type: 'charge',  is_detail: true  },
  { code: '6064', label: 'Achats fournitures informatiques',                type: 'charge',  is_detail: true  },
  { code: '608',  label: 'Achats de services',                             type: 'charge',  is_detail: true  },
  { code: '609',  label: 'Rabais, remises, ristournes obtenus sur achats', type: 'charge',  is_detail: true  },
  { code: '6091', label: 'RRR obtenus sur marchandises',                   type: 'charge',  is_detail: true  },
  { code: '6092', label: 'RRR obtenus sur matières premières',             type: 'charge',  is_detail: true  },
  { code: '61',   label: 'Transports',                                     type: 'charge',  is_detail: false },
  { code: '611',  label: 'Transports sur achats',                          type: 'charge',  is_detail: true  },
  { code: '612',  label: 'Transports sur ventes',                          type: 'charge',  is_detail: true  },
  { code: '613',  label: 'Transports pour le compte de tiers',             type: 'charge',  is_detail: true  },
  { code: '614',  label: 'Transports de marchandises et produits',         type: 'charge',  is_detail: true  },
  { code: '616',  label: 'Transports du personnel',                        type: 'charge',  is_detail: true  },
  { code: '618',  label: 'Autres frais de transport',                      type: 'charge',  is_detail: true  },
  { code: '62',   label: 'Services extérieurs A',                          type: 'charge',  is_detail: false },
  { code: '621',  label: 'Sous-traitance générale',                        type: 'charge',  is_detail: true  },
  { code: '622',  label: 'Locations et charges locatives',                 type: 'charge',  is_detail: false },
  { code: '6221', label: 'Loyers et charges locatives',                    type: 'charge',  is_detail: true  },
  { code: '6222', label: 'Redevances de location-financement',             type: 'charge',  is_detail: true  },
  { code: '623',  label: 'Redevances de concessions, brevets, licences',   type: 'charge',  is_detail: true  },
  { code: '624',  label: 'Entretien, réparations et maintenance',          type: 'charge',  is_detail: true  },
  { code: '625',  label: "Primes d'assurance",                             type: 'charge',  is_detail: false },
  { code: '6251', label: 'Assurances multirisque',                         type: 'charge',  is_detail: true  },
  { code: '6252', label: 'Assurances transport',                           type: 'charge',  is_detail: true  },
  { code: '6253', label: 'Assurances responsabilité civile',               type: 'charge',  is_detail: true  },
  { code: '6254', label: 'Assurances vie groupe',                          type: 'charge',  is_detail: true  },
  { code: '626',  label: 'Études, recherches et documentation',            type: 'charge',  is_detail: true  },
  { code: '627',  label: 'Publicité, publications et relations publiques', type: 'charge',  is_detail: true  },
  { code: '628',  label: 'Frais de télécommunications',                    type: 'charge',  is_detail: true  },
  { code: '63',   label: 'Services extérieurs B',                          type: 'charge',  is_detail: false },
  { code: '631',  label: 'Frais bancaires',                                type: 'charge',  is_detail: true  },
  { code: '632',  label: "Rémunérations d'intermédiaires et honoraires",   type: 'charge',  is_detail: false },
  { code: '6321', label: 'Commissions et courtages',                       type: 'charge',  is_detail: true  },
  { code: '6322', label: 'Honoraires (avocats, notaires, experts)',         type: 'charge',  is_detail: true  },
  { code: '6323', label: "Frais d'actes et de contentieux",                type: 'charge',  is_detail: true  },
  { code: '633',  label: 'Frais de formation du personnel',                type: 'charge',  is_detail: true  },
  { code: '634',  label: 'Redevances pour concessions',                    type: 'charge',  is_detail: true  },
  { code: '635',  label: 'Cotisations et dons',                            type: 'charge',  is_detail: true  },
  { code: '636',  label: 'Frais de recrutement et de mutation',            type: 'charge',  is_detail: true  },
  { code: '637',  label: 'Frais de réception et de représentation',        type: 'charge',  is_detail: true  },
  { code: '638',  label: 'Autres charges de services extérieurs B',        type: 'charge',  is_detail: true  },
  { code: '64',   label: 'Impôts et taxes',                                type: 'charge',  is_detail: false },
  { code: '641',  label: 'Impôts et taxes locaux',                         type: 'charge',  is_detail: false },
  { code: '6411', label: 'Contribution foncière',                          type: 'charge',  is_detail: true  },
  { code: '6412', label: 'TVA non déductible',                             type: 'charge',  is_detail: true  },
  { code: '6415', label: "Taxe d'apprentissage",                           type: 'charge',  is_detail: true  },
  { code: '6416', label: 'Taxe sur la formation professionnelle',          type: 'charge',  is_detail: true  },
  { code: '6417', label: 'Taxe professionnelle (patente)',                  type: 'charge',  is_detail: true  },
  { code: '6418', label: 'Taxe de résidence',                              type: 'charge',  is_detail: true  },
  { code: '642',  label: 'Impôts sur les traitements et salaires',         type: 'charge',  is_detail: false },
  { code: '6421', label: 'IRPP sur salaires',                              type: 'charge',  is_detail: true  },
  { code: '6422', label: 'CFCE (Contribution forfaitaire à charge employeur)', type: 'charge', is_detail: true },
  { code: '643',  label: "Taxes d'apprentissage",                          type: 'charge',  is_detail: true  },
  { code: '645',  label: "Taxes sur le chiffre d'affaires",                type: 'charge',  is_detail: true  },
  { code: '648',  label: 'Autres impôts et taxes',                         type: 'charge',  is_detail: true  },
  { code: '65',   label: 'Autres charges',                                 type: 'charge',  is_detail: false },
  { code: '651',  label: 'Pertes sur créances irrécouvrables',             type: 'charge',  is_detail: true  },
  { code: '652',  label: 'Quote-part de résultat sur opérations en commun', type: 'charge', is_detail: true  },
  { code: '653',  label: 'Jetons de présence',                             type: 'charge',  is_detail: true  },
  { code: '654',  label: 'Pertes sur opérations faites en commun',         type: 'charge',  is_detail: true  },
  { code: '658',  label: 'Charges diverses',                               type: 'charge',  is_detail: true  },
  { code: '66',   label: 'Charges financières',                            type: 'charge',  is_detail: false },
  { code: '661',  label: 'Intérêts des emprunts',                          type: 'charge',  is_detail: false },
  { code: '6611', label: 'Intérêts des emprunts bancaires',                type: 'charge',  is_detail: true  },
  { code: '6612', label: 'Intérêts sur obligations',                       type: 'charge',  is_detail: true  },
  { code: '662',  label: 'Intérêts des dettes de location-financement',    type: 'charge',  is_detail: true  },
  { code: '663',  label: 'Intérêts des comptes courants et dépôts créditeurs', type: 'charge', is_detail: true },
  { code: '664',  label: "Intérêts sur opérations de crédit-bail",         type: 'charge',  is_detail: true  },
  { code: '665',  label: 'Escomptes accordés',                             type: 'charge',  is_detail: true  },
  { code: '666',  label: 'Pertes de change',                               type: 'charge',  is_detail: true  },
  { code: '667',  label: 'Frais sur effets de commerce et de trésorerie',  type: 'charge',  is_detail: true  },
  { code: '668',  label: 'Autres charges financières',                     type: 'charge',  is_detail: true  },
  { code: '669',  label: 'Charges nettes sur cessions de titres de placement', type: 'charge', is_detail: true },
  { code: '67',   label: 'Charges salariales et sociales',                 type: 'charge',  is_detail: false },
  { code: '671',  label: 'Rémunérations du personnel',                     type: 'charge',  is_detail: false },
  { code: '6711', label: 'Salaires et appointements',                      type: 'charge',  is_detail: true  },
  { code: '6712', label: 'Primes et gratifications',                       type: 'charge',  is_detail: true  },
  { code: '6713', label: 'Indemnités et avantages divers',                 type: 'charge',  is_detail: true  },
  { code: '6714', label: 'Congés payés',                                   type: 'charge',  is_detail: true  },
  { code: '6718', label: 'Autres rémunérations',                           type: 'charge',  is_detail: true  },
  { code: '672',  label: 'Rémunérations du personnel extérieur',           type: 'charge',  is_detail: true  },
  { code: '674',  label: 'Charges sociales — employeur',                   type: 'charge',  is_detail: false },
  { code: '6741', label: 'CNSS patronale (Gabon)',                         type: 'charge',  is_detail: true  },
  { code: '6742', label: 'CNAMGS patronale (Gabon)',                       type: 'charge',  is_detail: true  },
  { code: '6743', label: "Fonds National de l'Habitat (FNH — Gabon)",      type: 'charge',  is_detail: true  },
  { code: '6748', label: 'Autres charges sociales',                        type: 'charge',  is_detail: true  },
  { code: '676',  label: 'Rémunérations du gérant associé',                type: 'charge',  is_detail: true  },
  { code: '678',  label: 'Charges sociales diverses',                      type: 'charge',  is_detail: true  },
  { code: '68',   label: 'Dotations aux amortissements et dépréciations',  type: 'charge',  is_detail: false },
  { code: '681',  label: "Dotations aux amortissements — actif immobilisé", type: 'charge', is_detail: false },
  { code: '6811', label: 'Dotations amort. immobilisations incorporelles', type: 'charge',  is_detail: true  },
  { code: '6812', label: 'Dotations amort. bâtiments',                    type: 'charge',  is_detail: true  },
  { code: '6813', label: 'Dotations amort. aménagements et installations', type: 'charge', is_detail: true  },
  { code: '6814', label: 'Dotations amort. matériel',                     type: 'charge',  is_detail: true  },
  { code: '6815', label: 'Dotations amort. matériel de transport',        type: 'charge',  is_detail: true  },
  { code: '682',  label: 'Dotations aux dépréciations — actif immobilisé', type: 'charge', is_detail: true  },
  { code: '683',  label: 'Dotations aux dépréciations — actif circulant', type: 'charge',  is_detail: true  },
  { code: '684',  label: 'Dotations aux provisions pour risques et charges', type: 'charge', is_detail: true },
  { code: '691',  label: 'Participation aux bénéfices du personnel',      type: 'charge',  is_detail: true  },

  // ══════════════════════════════════════════════════════
  //  CLASSE 7 — PRODUITS DES ACTIVITÉS ORDINAIRES
  // ══════════════════════════════════════════════════════
  { code: '70',   label: 'Ventes',                                          type: 'produit', is_detail: false },
  { code: '701',  label: 'Ventes de marchandises',                          type: 'produit', is_detail: true  },
  { code: '702',  label: 'Ventes de produits finis',                        type: 'produit', is_detail: true  },
  { code: '703',  label: 'Ventes de produits intermédiaires',               type: 'produit', is_detail: true  },
  { code: '704',  label: 'Ventes de produits résiduels',                    type: 'produit', is_detail: true  },
  { code: '705',  label: 'Travaux facturés',                                 type: 'produit', is_detail: true  },
  { code: '706',  label: 'Services vendus',                                  type: 'produit', is_detail: false },
  { code: '7061', label: 'Prestations de services médicales',               type: 'produit', is_detail: true  },
  { code: '7062', label: 'Consultations et honoraires',                     type: 'produit', is_detail: true  },
  { code: '7063', label: 'Hospitalisations',                                type: 'produit', is_detail: true  },
  { code: '7064', label: 'Examens et analyses',                             type: 'produit', is_detail: true  },
  { code: '7065', label: 'Prestations de services informatiques',           type: 'produit', is_detail: true  },
  { code: '7066', label: 'Commissions et courtages facturés',               type: 'produit', is_detail: true  },
  { code: '7068', label: 'Autres services vendus',                          type: 'produit', is_detail: true  },
  { code: '707',  label: 'Produits accessoires',                            type: 'produit', is_detail: true  },
  { code: '708',  label: 'Produits des activités annexes',                  type: 'produit', is_detail: true  },
  { code: '709',  label: 'Rabais, remises, ristournes accordés',            type: 'produit', is_detail: true  },
  { code: '71',   label: "Subventions d'exploitation",                      type: 'produit', is_detail: false },
  { code: '711',  label: "Subventions d'exploitation reçues",               type: 'produit', is_detail: true  },
  { code: '712',  label: "Subventions d'équilibre",                         type: 'produit', is_detail: true  },
  { code: '72',   label: 'Production immobilisée',                          type: 'produit', is_detail: false },
  { code: '721',  label: 'Immobilisations incorporelles produites',         type: 'produit', is_detail: true  },
  { code: '722',  label: 'Immobilisations corporelles produites',           type: 'produit', is_detail: true  },
  { code: '73',   label: 'Variations de stocks de produits finis et en cours', type: 'produit', is_detail: false },
  { code: '731',  label: 'Variations de stocks — produits finis',           type: 'produit', is_detail: true  },
  { code: '732',  label: 'Variations de stocks — produits en cours',        type: 'produit', is_detail: true  },
  { code: '74',   label: 'Autres produits',                                 type: 'produit', is_detail: false },
  { code: '741',  label: 'Indemnités et allocations diverses',              type: 'produit', is_detail: true  },
  { code: '742',  label: 'Cotisations des syndicats professionnels',        type: 'produit', is_detail: true  },
  { code: '744',  label: 'Contributions et libéralités reçues',             type: 'produit', is_detail: true  },
  { code: '745',  label: 'Quotes-parts de résultat positif',                type: 'produit', is_detail: true  },
  { code: '748',  label: 'Revenus des activités annexes',                   type: 'produit', is_detail: true  },
  { code: '75',   label: 'Reprises de provisions',                          type: 'produit', is_detail: false },
  { code: '751',  label: 'Reprises prov. pour risques et charges',          type: 'produit', is_detail: true  },
  { code: '752',  label: 'Reprises amortissements et dépréciations',        type: 'produit', is_detail: true  },
  { code: '753',  label: "Reprises dépréciations actif immobilisé",         type: 'produit', is_detail: true  },
  { code: '754',  label: 'Reprises dépréciations stocks',                   type: 'produit', is_detail: true  },
  { code: '755',  label: 'Reprises dépréciations comptes de tiers',         type: 'produit', is_detail: true  },
  { code: '76',   label: "Transferts de charges d'exploitation",            type: 'produit', is_detail: false },
  { code: '761',  label: "Transferts de charges d'exploitation",            type: 'produit', is_detail: true  },
  { code: '77',   label: 'Revenus financiers',                              type: 'produit', is_detail: false },
  { code: '771',  label: 'Intérêts et produits assimilés',                  type: 'produit', is_detail: true  },
  { code: '772',  label: 'Revenus de titres de placement',                  type: 'produit', is_detail: true  },
  { code: '773',  label: 'Revenus de créances',                             type: 'produit', is_detail: true  },
  { code: '774',  label: 'Gains de change',                                 type: 'produit', is_detail: true  },
  { code: '775',  label: 'Escomptes obtenus',                               type: 'produit', is_detail: true  },
  { code: '776',  label: 'Dividendes reçus',                                type: 'produit', is_detail: true  },
  { code: '777',  label: 'Gains nets sur cessions de titres de placement',  type: 'produit', is_detail: true  },
  { code: '778',  label: 'Autres revenus financiers',                       type: 'produit', is_detail: true  },
  { code: '78',   label: 'Transferts de charges financières',               type: 'produit', is_detail: false },
  { code: '781',  label: 'Transferts de charges financières',               type: 'produit', is_detail: true  },
  { code: '79',   label: 'Reprises de provisions financières',              type: 'produit', is_detail: false },
  { code: '791',  label: 'Reprises prov. pour risques financiers',          type: 'produit', is_detail: true  },
  { code: '794',  label: 'Reprises prov. pour pertes de change',            type: 'produit', is_detail: true  },

  // ══════════════════════════════════════════════════════
  //  CLASSE 8 — AUTRES CHARGES ET PRODUITS (HAO)
  // ══════════════════════════════════════════════════════
  { code: '81',   label: "Valeurs comptables des cessions d'immobilisations", type: 'charge', is_detail: false },
  { code: '811',  label: 'V.C. cessions — immob. incorporelles',            type: 'charge',  is_detail: true  },
  { code: '812',  label: 'V.C. cessions — terrains',                        type: 'charge',  is_detail: true  },
  { code: '813',  label: 'V.C. cessions — bâtiments',                       type: 'charge',  is_detail: true  },
  { code: '814',  label: 'V.C. cessions — matériel',                        type: 'charge',  is_detail: true  },
  { code: '815',  label: 'V.C. cessions — matériel de transport',           type: 'charge',  is_detail: true  },
  { code: '816',  label: 'V.C. cessions — immob. financières',              type: 'charge',  is_detail: true  },
  { code: '82',   label: "Produits des cessions d'immobilisations",          type: 'produit', is_detail: false },
  { code: '821',  label: 'Produits cessions — immob. incorporelles',        type: 'produit', is_detail: true  },
  { code: '822',  label: 'Produits cessions — terrains',                    type: 'produit', is_detail: true  },
  { code: '823',  label: 'Produits cessions — bâtiments',                   type: 'produit', is_detail: true  },
  { code: '824',  label: 'Produits cessions — matériel',                    type: 'produit', is_detail: true  },
  { code: '825',  label: 'Produits cessions — matériel de transport',       type: 'produit', is_detail: true  },
  { code: '826',  label: 'Produits cessions — immob. financières',          type: 'produit', is_detail: true  },
  { code: '83',   label: 'Charges HAO',                                     type: 'charge',  is_detail: false },
  { code: '831',  label: 'Charges HAO courantes',                           type: 'charge',  is_detail: true  },
  { code: '832',  label: 'Amendes et pénalités (HAO)',                      type: 'charge',  is_detail: true  },
  { code: '833',  label: 'Pertes sur créances HAO',                         type: 'charge',  is_detail: true  },
  { code: '835',  label: 'Fonds de développement régional (Gabon)',         type: 'charge',  is_detail: true  },
  { code: '838',  label: 'Charges HAO diverses',                            type: 'charge',  is_detail: true  },
  { code: '84',   label: 'Produits HAO',                                    type: 'produit', is_detail: false },
  { code: '841',  label: 'Produits HAO courants',                           type: 'produit', is_detail: true  },
  { code: '842',  label: 'Produits de récupération (HAO)',                   type: 'produit', is_detail: true  },
  { code: '843',  label: 'Libéralités reçues (HAO)',                        type: 'produit', is_detail: true  },
  { code: '848',  label: 'Produits HAO divers',                             type: 'produit', is_detail: true  },
  { code: '85',   label: 'Dotations HAO',                                   type: 'charge',  is_detail: false },
  { code: '851',  label: 'Dotations aux amortissements HAO',                type: 'charge',  is_detail: true  },
  { code: '852',  label: 'Dotations aux provisions HAO',                    type: 'charge',  is_detail: true  },
  { code: '86',   label: 'Reprises HAO',                                    type: 'produit', is_detail: false },
  { code: '861',  label: "Reprises d'amortissements HAO",                   type: 'produit', is_detail: true  },
  { code: '862',  label: 'Reprises de provisions HAO',                      type: 'produit', is_detail: true  },
  { code: '87',   label: 'Participation des travailleurs',                  type: 'charge',  is_detail: false },
  { code: '871',  label: 'Participation des salariés aux bénéfices',        type: 'charge',  is_detail: true  },
  { code: '88',   label: "Subventions d'équilibre",                         type: 'produit', is_detail: false },
  { code: '881',  label: "Subventions d'équilibre reçues",                  type: 'produit', is_detail: true  },
  { code: '89',   label: 'Impôts sur le résultat',                          type: 'charge',  is_detail: false },
  { code: '891',  label: 'Impôt sur les sociétés (IS)',                     type: 'charge',  is_detail: true  },
  { code: '892',  label: 'Impôt minimum forfaitaire (IMF — Gabon)',          type: 'charge',  is_detail: true  },
  { code: '893',  label: 'Contribution spéciale sur les revenus (CSR — Gabon)', type: 'charge', is_detail: true },
  { code: '894',  label: 'Retenues à la source (RAS)',                      type: 'charge',  is_detail: true  },
  { code: '899',  label: 'Autres impôts sur résultat',                      type: 'charge',  is_detail: true  },
];

async function main() {
  console.log('VISION R+ — Plan Comptable OHADA complet (classes 1 à 8, adapté Gabon)...');

  const result = await prisma.account.createMany({
    data: ohada.map((c) => ({
      code:       c.code,
      label:      c.label,
      type:       c.type as any,
      system:     'ohada' as any,
      is_detail:  c.is_detail,
      company_id: null,
    })),
    skipDuplicates: true,
  });

  const total  = await prisma.account.count({ where: { system: 'ohada', company_id: null } });
  const detail = await prisma.account.count({ where: { system: 'ohada', company_id: null, is_detail: true } });

  console.log(`Comptes insérés : ${result.count}`);
  console.log(`Total OHADA : ${total} comptes dont ${detail} mouvementables`);
  console.log('TERMINÉ !');
}

main()
  .catch((e) => { console.error('Erreur seed :', e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
